# Module 9:- Working with pandas
# why we learning pandas
#  in previous lectures we learned numpy which is very powerful for numerical computation
# however real-world dataset are rarely pure numerical matrices.
    # real dataset contains:
        # 1.names
        # 2.dates
        # 3.categories
        # 4.missing values
        # 5.mixed dat types

# example dataset
# name   |age | salary|
# --------------------|
# rahul  |25  | 5ok   |
# priya  |28  | 65k   |
# aman   |24  |  48k  |

# numpy is a python library used for data analysis and data manipulation
# It provides powerful tools to:
    # Organize structured data
    # Clean messy datasets
    # Perform statistical analysis
    # Prepare data for machine learning

# Pandas works on top of NumPy.
# This means:
    # NumPy → numerical engine
    # Pandas → data analysis toolkit



# Why Pandas is Important

# Pandas is widely used in:
# Data Science
    # Cleaning and preparing datasets
# Data Analytics
    # Analyzing business data
# Finance
    # Stock market analysis
# Machine Learning
    # Preparing datasets for models
# Research
    # Handling large experimental datasets


# Key Features of Pandas
    # • Handles tabular data easily 
    # • Supports missing values
    # • Powerful indexing and filtering
    # • Built-in statistical functions
    # • Easy file reading (CSV, Excel, SQL)



# Two Core Data Structures in Pandas
# Pandas mainly provides two data structures:

# 1. Series:A Series is a one-dimensional labeled array.

        # It is similar to:
            # • A column in a table
            # • A NumPy array with labels


            # Structure of a Series:
            # Index → labels
            # Values → actual data
            # Example:
            #     Index Value
            #       0     10
            #       1     20
            #       2     30

In [1]:
import pandas as pd
# example:
# creating a series
data=pd.Series([10,20,30,40])
print(data)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
#2. Custom Index in Series : We can also define our own labels for the Series.
# example:
data=pd.Series([100,200,300],index=["A","B","C"])
print(data)

A    100
B    200
C    300
dtype: int64

2.pandas Dataframe
A DataFrame is a two-dimensional table.
It is similar to:
• Excel spreadsheet
• SQL table
• Dataset used in data science
Example structure:
Name   Age  Salary
Rahul  25   50000
Priya  28   65000
Aman   24   48000

In [3]:
data={"name":["rahul","priya","aman"],
      "age":[25,28,24],
      "salary":[50000,65000,48000]}

df=pd.DataFrame(data)
data

{'name': ['rahul', 'priya', 'aman'],
 'age': [25, 28, 24],
 'salary': [50000, 65000, 48000]}

Observations
In a DataFrame:
Rows → represent observations
Columns → represent variables
Each column can have a different data type:
Name → string
Age → integer
Salary → integer

session2=reading and writiing data
in real project we rarely crate dataset mannualy
insted we load dataset from such as:
1.cvs files
2.excel file
3.dataframes
pandas provides functions to easily read and write these files

>reading cvs file
cvs stands for:
comma separated values
syntax:pd.read_cvs("filename.cvs")

In [4]:
df=pd.read_csv("D:\DA&DS\pandas\california_housing_test.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\dhruv\AppData\Local\Temp\ipykernel_15748\2326284778.py:1: SyntaxWarning: invalid escape sequence '\D'
  df=pd.read_csv("D:\DA&DS\pandas\california_housing_test.csv")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

viewing Dataset:
when dataset are large,we usually inspect the first few rows
useful function:
head()->>first 5 rows
tail()->>last 5 rows

In [5]:
print("first 5 rows of dataset")
df.head()

first 5 rows of dataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [6]:
print("last 5 rows of dataset")
df.tail()

last 5 rows of dataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

Dataset summary information
Two very important functions:
info()
shows:
#number of rows
#numbers of column
#datatype
#missing values

describe():
provides statistical summary

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [8]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

Exporting data:
pandas also allows exporting dataset.
Export to cvs:
df.to_cvs("output.cvs")
Export to excel:
df.toexcel("output.xlsx")

In [9]:
df.to_csv("output.xlsx")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

#session 3--selecting & filtering Data in dandas
            in real-world data analysis,we rarely use the entire dataset

most of the time we need to:
#select specific column
#select specific rows
#filter rows based on conditions
#query important information from the datset

pandas provide powerful tools for selecting and filtering data

the two most important methods are:
1.loc->label based selection
2.iloc->position based selection

step 1:-create a sample Dataset:
we will crate a small dataset of customers.
columns include:
    #customer name
    #city
    #revenue

In [10]:
data={
    "customer":["aman","priya","rahul","sneha","karan"],
    "city":["delhi","mumbai","delhi","banglore","mumbai"],
    "revenue":[12000,8000,15000,7000,20000]
}
df=pd.DataFrame(data)
df

  customer      city  revenue
0     aman     delhi    12000
1    priya    mumbai     8000
2    rahul     delhi    15000
3    sneha  banglore     7000
4    karan    mumbai    20000

>selecting columns
we can select column using the column name.
syntax:df["column_name"]

In [11]:
df["revenue"]

0    12000
1     8000
2    15000
3     7000
4    20000
Name: revenue, dtype: int64

>selecting multiple columns
syntax:df[["column1","column2"]]

In [12]:
df[["customer","revenue"]]

  customer  revenue
0     aman    12000
1    priya     8000
2    rahul    15000
3    sneha     7000
4    karan    20000

>selecting rows using loc:
loc select rows based on labels or index values.

df.loc[row_index]
df.loc[row_index,column_index]

In [13]:
#selecting rows first
df.loc[0]

customer     aman
city        delhi
revenue     12000
Name: 0, dtype: object

In [14]:
#select specific values
df.loc[2,"revenue"]

np.int64(15000)

>selecting rows using iloc:
iloc select rows using numerical positions.

syntax:
df.iloc[row_position]
df.iloc[row_position,column_position]

>>>Simple Memory Trick
loc → “location by name”
iloc → “integer location”

In [15]:
# select third row
df.iloc[2]

customer    rahul
city        delhi
revenue     15000
Name: 2, dtype: object

In [16]:
# select specific values
df.iloc[2,2]

np.int64(15000)

>boolean filtering

filtering means selecting rows based on conditions.
example:
find customers whose revenue is grater than 10000.

In [17]:
df[df["revenue"]>10000]

  customer    city  revenue
0     aman   delhi    12000
2    rahul   delhi    15000
4    karan  mumbai    20000

In [18]:
#customers with revenue>10000 and city="delhi"
df[(df["revenue"]>10000)&(df["city"]=="delhi")]

  customer   city  revenue
0     aman  delhi    12000
2    rahul  delhi    15000

>Querying Data
pandas also provides the query() method
syntax:df.query("condition")

In [19]:
df.query("revenue>10000")

  customer    city  revenue
0     aman   delhi    12000
2    rahul   delhi    15000
4    karan  mumbai    20000

>Example case study:
select customers whose revenues is grater than 10000.

In [20]:
high_revenue_customers=df[df["revenue"]>10000]
high_revenue_customers

  customer    city  revenue
0     aman   delhi    12000
2    rahul   delhi    15000
4    karan  mumbai    20000

#session:4--sorting & rendexing 
sorting is an important operation when analyzing data.
example:
    #sorting product by ;price
    #ranking student by marks
    #sorting customers by revenue

pandas provides functions for sorting rows and indices.


#sorting values:
function:sort_value()
syntax:df.sort_value(by="column_name")

In [21]:
df.sort_values(by="revenue")

  customer      city  revenue
3    sneha  banglore     7000
1    priya    mumbai     8000
0     aman     delhi    12000
2    rahul     delhi    15000
4    karan    mumbai    20000

>sorting in sescending order:
we can sort values in descending order using: ascending=false

In [22]:
df.sort_values(by="revenue",ascending=False)

  customer      city  revenue
4    karan    mumbai    20000
2    rahul     delhi    15000
0     aman     delhi    12000
1    priya    mumbai     8000
3    sneha  banglore     7000

>sorting multiple columns
syntax:df.sort_values(by=["column1","column2"])

In [23]:
df.sort_values(by=["city","revenue"])

  customer      city  revenue
3    sneha  banglore     7000
0     aman     delhi    12000
2    rahul     delhi    15000
1    priya    mumbai     8000
4    karan    mumbai    20000

>sorting by index:
we can also sort rows based on index values.
fuction:sort_index()

In [24]:
df.sort_index()

  customer      city  revenue
0     aman     delhi    12000
1    priya    mumbai     8000
2    rahul     delhi    15000
3    sneha  banglore     7000
4    karan    mumbai    20000

>resetting index:
after filtering or sorting,index numbers may become irregular.
we can reset them using:
reset_index()

In [25]:
sorted_df=df.sort_values(by="revenue")
sorted_df.reset_index()

   index customer      city  revenue
0      3    sneha  banglore     7000
1      1    priya    mumbai     8000
2      0     aman     delhi    12000
3      2    rahul     delhi    15000
4      4    karan    mumbai    20000

>removing old index:
we can drop the old index using:
reset_index(drop=true)

In [26]:
sorted_df.reset_index(drop=True)

  customer      city  revenue
0    sneha  banglore     7000
1    priya    mumbai     8000
2     aman     delhi    12000
3    rahul     delhi    15000
4    karan    mumbai    20000

>Reindexing Data
reindexing allows us to reorder or redefine the index.
syntax:df.reindex(new_index)

In [27]:
df.reindex([4,3,2,1,0])

  customer      city  revenue
4    karan    mumbai    20000
3    sneha  banglore     7000
2    rahul     delhi    15000
1    priya    mumbai     8000
0     aman     delhi    12000

>Demo case study:
sort product by revenue in descending order.

In [28]:
df.sort_values(by="revenue",ascending=False)

  customer      city  revenue
4    karan    mumbai    20000
2    rahul     delhi    15000
0     aman     delhi    12000
1    priya    mumbai     8000
3    sneha  banglore     7000

>Practice question=pandas(selecting,filtering,sorting)
use the following dataset for all questions.

In [29]:
data1={"Customer": ["Aman", "Priya", "Rahul", "Sneha", "Karan"],
       "City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"],
        "Revenue": [12000, 8000, 15000, 7000, 20000]
      }
df1=pd.DataFrame(data1)

1.Display the entire dataset.
2.Select only the Revenue column.
3.Select the Customer and Revenue columns together.
4.Using loc, display the second row of the dataset.
5.Using iloc, display the third row of the dataset.
6.Using loc, retrieve the Revenue value of Rahul.
7.Filter the dataset to show customers whose Revenue is greater than 10000.
8.Display customers who belong to Mumbai.

In [30]:
# 1
df1

  Customer       City  Revenue
0     Aman      Delhi    12000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
3    Sneha  Bangalore     7000
4    Karan     Mumbai    20000

In [31]:
# 2
df1["Revenue"]

0    12000
1     8000
2    15000
3     7000
4    20000
Name: Revenue, dtype: int64

In [32]:
# 3
df1[["Customer","Revenue"]]

  Customer  Revenue
0     Aman    12000
1    Priya     8000
2    Rahul    15000
3    Sneha     7000
4    Karan    20000

In [33]:
# 4
df1.loc[1]

Customer     Priya
City        Mumbai
Revenue       8000
Name: 1, dtype: object

In [34]:
# 5
df1.iloc[2]

Customer    Rahul
City        Delhi
Revenue     15000
Name: 2, dtype: object

In [35]:
# 6
df1.loc[2,"Revenue"]

np.int64(15000)

In [36]:
# 7
df1[df1["Revenue"]>10000]

  Customer    City  Revenue
0     Aman   Delhi    12000
2    Rahul   Delhi    15000
4    Karan  Mumbai    20000

In [37]:
# 8
df1[df1["City"]=="Mumbai"]

  Customer    City  Revenue
1    Priya  Mumbai     8000
4    Karan  Mumbai    20000

#sesion=5:handling missing values in pandas:

why handling missing value is important

in real-world dataset,it is very comman to encounter missing values

example:
| Customer | Age | City  |
|----------|-----|------ |
| Aman     | 25  | Delhi |
| Priya    | NaN | Mumbai|
| Rahul    | 30  | Delhi |

missing values can occur due to:
    #data entry error
    #incomplete forms
    #system failures
    #data collection issues

if missing values are not handled properly,they can cause:
    #incorrect analysis
    #errors in machine learing models
    #biased result

therefore data celaning is a critical step in data analysis.
_______________________________________________
Identifying missing values

pandas represents missing values using NaN.
function:isnull()
syntax:df.isnull()

purpose:
return a boolean Dataframe where:
True->values is missing
False->values is present

In [38]:
import pandas as pd
import numpy as np
data2= {
    "Customer": ["Aman", "Priya", "Rahul", "Sneha"],
    "Age": [25, np.nan, 30, np.nan],
    "City": ["Delhi", "Mumbai", "Delhi", "Bangalore"]
}

df2 = pd.DataFrame(data2)

df2

  Customer   Age       City
0     Aman  25.0      Delhi
1    Priya   NaN     Mumbai
2    Rahul  30.0      Delhi
3    Sneha   NaN  Bangalore

In [39]:
df2.isnull()

   Customer    Age   City
0     False  False  False
1     False   True  False
2     False  False  False
3     False   True  False

Counting missing values:
To count missing values per column we use:
df.isnull().sum()

In [40]:
df2.isnull().sum()

Customer    0
Age         2
City        0
dtype: int64

>Removing misssing values:
function:dropna()
syntax:df.dropna(axis=0,hou='any')
parameters:
axis:0-remove rows
     1:remove columns
hou:'any'-drop if any values is missing
    'all'-drop if all values are missing

In [41]:
df2.dropna()

  Customer   Age   City
0     Aman  25.0  Delhi
2    Rahul  30.0  Delhi

In [42]:
df2.dropna(axis=0)

  Customer   Age   City
0     Aman  25.0  Delhi
2    Rahul  30.0  Delhi

In [43]:
df2.dropna(axis=0,how='any')

  Customer   Age   City
0     Aman  25.0  Delhi
2    Rahul  30.0  Delhi

Rows removed:

Row 1 → Age missing
Row 2 → City missing
Row 3 → Age & City missing
Row 4 → All missing

In [44]:
df2.dropna(axis=0,how='all')

  Customer   Age       City
0     Aman  25.0      Delhi
1    Priya   NaN     Mumbai
2    Rahul  30.0      Delhi
3    Sneha   NaN  Bangalore

In [45]:
df2.dropna(axis=1,how='any')

  Customer       City
0     Aman      Delhi
1    Priya     Mumbai
2    Rahul      Delhi
3    Sneha  Bangalore

>filling missing values
insted of removing rows,we may replace missing values.
function:fillna()
syntax:df.fill(value)

common strategies:
    #replace with mean
    #replace with median
    #replace with constant value

In [46]:
df2["Age"].fillna(df2["Age"].mean())

0    25.0
1    27.5
2    30.0
3    27.5
Name: Age, dtype: float64

>Replace missing values with median
median is often preferred when data contains ouytliers

In [47]:
df2["Age"].fillna(df2["Age"].median())

0    25.0
1    27.5
2    30.0
3    27.5
Name: Age, dtype: float64

case study-celaning missing age
goal:replace missing ages using average age.

In [48]:
df2["Age"]=df2["Age"].fillna(df2["Age"].mean())
df2

  Customer   Age       City
0     Aman  25.0      Delhi
1    Priya  27.5     Mumbai
2    Rahul  30.0      Delhi
3    Sneha  27.5  Bangalore

>Handling miissing  values in categorical columns:
pandas supports munltiple data types in a dataframe sucu as:
    #numerical:Age,salary
    #categorical:city,gender,product
    #boolean: True/False
    #Datetime:Dates
missing values (NaN) can exist in any type of column,not just numerical
______________________________________________
important clarification:
 #dropna() works on all columns
 #fillna() works on all columns

 BUT:
 the way we fill missing values depends on the data type
 _______________________________________________
 handling numerical vs categorical data
  numerical columns:
    #replace with mean
    #replace with median
 categorical columns:
    #replace with mode(most frequent value)
    #repllace with constant like "unknow"
________________________________________________
why mean dose not work for categorical data

example:
city column:
delhi,mumbai,NaN
we cannot calculate mean of "delhi" ad "mumbai"

so we use:
mode(most frequant value)
constant value like "unknow"

In [49]:
import pandas as pd
import numpy as np

data3= {
    "Customer": ["Aman", "Priya", "Rahul", "Sneha"],
    "Age": [25, np.nan, 30, np.nan],          # Numerical
    "City": ["Delhi", np.nan, "Delhi", "Mumbai"]  # Categorical
}

df3 = pd.DataFrame(data3)

print("Original DataFrame:\n")
print(df3)

Original DataFrame:

  Customer   Age    City
0     Aman  25.0   Delhi
1    Priya   NaN     NaN
2    Rahul  30.0   Delhi
3    Sneha   NaN  Mumbai

1.filling numerical coilumn(Age):
use mean or median

In [50]:
df3["Age"]=df3["Age"].fillna(df3["Age"].mean())

2.filling categorical column using mode.
mode=most frequent value

In [51]:
df3["City"]=df3["City"].fillna(df3["City"].mode())
df3

  Customer   Age    City
0     Aman  25.0   Delhi
1    Priya  27.5     NaN
2    Rahul  30.0   Delhi
3    Sneha  27.5  Mumbai

3.filling categorical column using constant.
insted of mode,we can use a constant value.
example:"unknow"

In [52]:
df3["City"]=df3["City"].fillna("unknow")
df3

  Customer   Age    City
0     Aman  25.0   Delhi
1    Priya  27.5  unknow
2    Rahul  30.0   Delhi
3    Sneha  27.5  Mumbai

4.using fillna() for multuple columns.

we can handel both numeroical and categorical column todether.

example:
#age-replace with mean
#city-replace with "unknow"

In [53]:
df3=df3.fillna({"Age":df3["Age"].mean(),
                "City":"unknow"})
df3

  Customer   Age    City
0     Aman  25.0   Delhi
1    Priya  27.5  unknow
2    Rahul  30.0   Delhi
3    Sneha  27.5  Mumbai

#session 6==handling duplicates vand outliers
    two comman problems in dataset:
    #duplicate records
    #outliers(extreme value)
    both can distort analysis result.
    _____________________________________________
    >handling duplicate rows:
    function:drop_duplicates()

    syntax:df.drop_duplicates()

    purpose:remove duplicate rows from the dataset

    parameter:
    subset
    specify column(s) to check duplicates keep

    'first'->keep first occurrence
    'last'->keep last occurrence
    'false'->remove all duplicates

In [54]:
data4={"customer":["aman","priya","aman","rahul"],
       "sales":[500,700,500,900]}
df4=pd.DataFrame(data4)
df4

  customer  sales
0     aman    500
1    priya    700
2     aman    500
3    rahul    900

In [55]:
df4.drop_duplicates()

  customer  sales
0     aman    500
1    priya    700
3    rahul    900

>what is outliers??
outliers are extreme values that differ significantly from other observations.

examples:[10,12,11,13,500]
so value 500 is an outlier.

outliers can occure due to:
    #measurement errors
    #data entry errors
    #unusual events

>detecting outliers using iqr method
iqr=interquartile range
formula:iqr=q3-q1
lower bound=q1-1.5*iqr
upper bound=q3+1.5*iqr

In [56]:
salse=pd.Series([100,120,130,110,115,500])

q1=salse.quantile(0.25)
q3=salse.quantile(0.75)

iqr=q3-q1

lower=q1-1.5*iqr
upper=q3+1.5*iqr

outliers=salse[(salse<lower)|(salse>upper)]
outliers

5    500
dtype: int64

>Z-score concept:
Z-score mesures how far a value is from the mean

formula:Z=(X-Mean)/standard deciation

values with |Z|>3 are often considered outliers.

In [57]:
mean=salse.mean()
std=salse.std()

z_score=(salse-mean)/std
z_score

0   -0.502667
1   -0.375677
2   -0.312182
3   -0.439172
4   -0.407425
5    2.037123
dtype: float64

#session 7=column operations & data tranformation
    in data analysis we often need to:
        #create new column
        #modify exisiting column
        #apply function to column

pandas provide serveral methods to perform tranformations.
___________________________________________
>adding new column
a new column can be create using assignment

example:price*quantity

In [58]:
data5={"product":["pen","notebook","marker"],
       "price":[10,50,20],
       "qty":[100,40,60]}

df5=pd.DataFrame(data5)
df5

    product  price  qty
0       pen     10  100
1  notebook     50   40
2    marker     20   60

In [59]:
df5["revenue"]=df5["price"]*df5["qty"]
df5

    product  price  qty  revenue
0       pen     10  100     1000
1  notebook     50   40     2000
2    marker     20   60     1200

>using apply():
apply() allows applying a function to columns.

syntax:df["column"].apply(function)

commonly used custom tranformation

In [60]:
df5["price_with_tax"]=df5["price"].apply(lambda x:x*1.18)
df5

    product  price  qty  revenue  price_with_tax
0       pen     10  100     1000            11.8
1  notebook     50   40     2000            59.0
2    marker     20   60     1200            23.6

>using lambda functions:
lambda function are samll anonymous functions.

stntax:lambda argument:expression
_______________________________________________
>usiing applymap()
applymap() applies a function to every element to the dataframe.

syntax:df.applymap(function)

note:used on;ly for dataframes(not series.)

In [61]:
df_numeric=df5[["price","qty"]]
df_numeric.map(lambda x:x*2)

   price  qty
0     20  200
1    100   80
2     40  120

In [62]:
# case study
# revenue=price*qty
df5["revenue"]

0    1000
1    2000
2    1200
Name: revenue, dtype: int64

In [63]:
# calculate total revenue
total_revenue=df5["revenue"].sum()
total_revenue

np.int64(4200)

In [64]:
# practice question
df6=pd.DataFrame({"name": ["Aman", "Priya", "Rahul", "Sneha", "Amit", "Priya", "Ravi", "Neha"],
                  "age": [25, 30, np.nan, 28, 40, 30, 120, 27],
                  "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Mumbai", "Delhi", None],
                  "salary": [50000, 60000, 55000, np.nan, 90000, 60000, 1000000, 52000]})

df6

    name    age    city     salary
0   Aman   25.0   Delhi    50000.0
1  Priya   30.0  Mumbai    60000.0
2  Rahul    NaN   Delhi    55000.0
3  Sneha   28.0    Pune        NaN
4   Amit   40.0  Mumbai    90000.0
5  Priya   30.0  Mumbai    60000.0
6   Ravi  120.0   Delhi  1000000.0
7   Neha   27.0     NaN    52000.0

In [65]:
print("display only the age column")
df6["age"]

display only the age column

0     25.0
1     30.0
2      NaN
3     28.0
4     40.0
5     30.0
6    120.0
7     27.0
Name: age, dtype: float64

In [66]:
print("display name ans salary together")
df6[["age","salary"]]

display name ans salary together

     age     salary
0   25.0    50000.0
1   30.0    60000.0
2    NaN    55000.0
3   28.0        NaN
4   40.0    90000.0
5   30.0    60000.0
6  120.0  1000000.0
7   27.0    52000.0

In [67]:
print("select 3rd using the iloc")
df6.iloc[2]

select 3rd using the iloc

name        Rahul
age           NaN
city        Delhi
salary    55000.0
Name: 2, dtype: object

In [68]:
print("select the salary of the 2nd rows using loc")
df6.loc[1,"salary"]

select the salary of the 2nd rows using loc

np.float64(60000.0)

In [69]:
print("show rows where salary>50000")
df6[df6["salary"]>50000]

show rows where salary>50000

    name    age    city     salary
1  Priya   30.0  Mumbai    60000.0
2  Rahul    NaN   Delhi    55000.0
4   Amit   40.0  Mumbai    90000.0
5  Priya   30.0  Mumbai    60000.0
6   Ravi  120.0   Delhi  1000000.0
7   Neha   27.0     NaN    52000.0

In [70]:
print("show rows where city is Delhi")
df6[df6["city"]=="Delhi"]

show rows where city is Delhi

    name    age   city     salary
0   Aman   25.0  Delhi    50000.0
2  Rahul    NaN  Delhi    55000.0
6   Ravi  120.0  Delhi  1000000.0

In [71]:
print("apply multiple conditions")
df6[(df6["salary"]>40000)&(df6["city"]=="Mumbai")]

apply multiple conditions

    name   age    city   salary
1  Priya  30.0  Mumbai  60000.0
4   Amit  40.0  Mumbai  90000.0
5  Priya  30.0  Mumbai  60000.0

In [72]:
print("sort salary in ascending order")
df6.sort_values("salary")

sort salary in ascending order

    name    age    city     salary
0   Aman   25.0   Delhi    50000.0
7   Neha   27.0     NaN    52000.0
2  Rahul    NaN   Delhi    55000.0
1  Priya   30.0  Mumbai    60000.0
5  Priya   30.0  Mumbai    60000.0
4   Amit   40.0  Mumbai    90000.0
6   Ravi  120.0   Delhi  1000000.0
3  Sneha   28.0    Pune        NaN

In [73]:
print("sort salary in descending order")
sorting=df6.sort_values("salary",ascending=False)
sorting

sort salary in descending order

    name    age    city     salary
6   Ravi  120.0   Delhi  1000000.0
4   Amit   40.0  Mumbai    90000.0
1  Priya   30.0  Mumbai    60000.0
5  Priya   30.0  Mumbai    60000.0
2  Rahul    NaN   Delhi    55000.0
7   Neha   27.0     NaN    52000.0
0   Aman   25.0   Delhi    50000.0
3  Sneha   28.0    Pune        NaN

In [74]:
print("after sorting reset index")
sorting.reset_index()

after sorting reset index

   index   name    age    city     salary
0      6   Ravi  120.0   Delhi  1000000.0
1      4   Amit   40.0  Mumbai    90000.0
2      1  Priya   30.0  Mumbai    60000.0
3      5  Priya   30.0  Mumbai    60000.0
4      2  Rahul    NaN   Delhi    55000.0
5      7   Neha   27.0     NaN    52000.0
6      0   Aman   25.0   Delhi    50000.0
7      3  Sneha   28.0    Pune        NaN

In [75]:
print("remove the old index")
sorting.reset_index(drop=True)

remove the old index

    name    age    city     salary
0   Ravi  120.0   Delhi  1000000.0
1   Amit   40.0  Mumbai    90000.0
2  Priya   30.0  Mumbai    60000.0
3  Priya   30.0  Mumbai    60000.0
4  Rahul    NaN   Delhi    55000.0
5   Neha   27.0     NaN    52000.0
6   Aman   25.0   Delhi    50000.0
7  Sneha   28.0    Pune        NaN

In [76]:
print("detect missing value using isnull()")
df6.isnull()

detect missing value using isnull()

    name    age   city  salary
0  False  False  False   False
1  False  False  False   False
2  False   True  False   False
3  False  False  False    True
4  False  False  False   False
5  False  False  False   False
6  False  False  False   False
7  False  False   True   False

In [77]:
print("count missing value per column")
df6.isnull().sum()

count missing value per column

name      0
age       1
city      1
salary    1
dtype: int64

In [78]:
print("drop rows with missing value")
df6.dropna()

drop rows with missing value

    name    age    city     salary
0   Aman   25.0   Delhi    50000.0
1  Priya   30.0  Mumbai    60000.0
4   Amit   40.0  Mumbai    90000.0
5  Priya   30.0  Mumbai    60000.0
6   Ravi  120.0   Delhi  1000000.0

In [79]:
# this only for understand do not run this line becuz this is drop column is any have a nan
# print("drop column with missing values")
# df6=df6.dropna(axis=1,how="all")
# df6

In [80]:
print("replace missing age with mean")
df6["age"]=df6["age"].fillna(df6["age"].mean())
df6["age"]

replace missing age with mean

0     25.000000
1     30.000000
2     42.857143
3     28.000000
4     40.000000
5     30.000000
6    120.000000
7     27.000000
Name: age, dtype: float64

In [81]:
print("repalace missing city with unknow")
df6["city"].fillna("unknow")

repalace missing city with unknow

0     Delhi
1    Mumbai
2     Delhi
3      Pune
4    Mumbai
5    Mumbai
6     Delhi
7    unknow
Name: city, dtype: str

In [82]:
df7=pd.Series([100,120,110,115,500])
# detect outliuers
df7

0    100
1    120
2    110
3    115
4    500
dtype: int64

In [83]:
q1=df7.quantile(0.25)
q3=df7.quantile(0.75)

iqr=q3-q1

lower=q1-1.5*iqr
upper=q3+1.5*iqr

outliers=df7[(df7<lower)|(df7>upper)]
outliers

4    500
dtype: int64

In [84]:
print("calculate z_score for each value")
mean=df7.mean()
std=df7.std()
z_score=(df7-mean)/std
z_score

calculate z_score for each value

0   -0.511460
1   -0.396526
2   -0.453993
3   -0.425259
4    1.787238
dtype: float64

In [85]:
print("identyfy where z_score>2")
df7[z_score>2]

identyfy where z_score>2

Series([], dtype: int64)

In [86]:
# 13
df8=pd.DataFrame({"product":["A","B","C","D"],
                  "price":[1000,2000,3000,4000],
                  "quantity":[1,2,3,4]})
df8

  product  price  quantity
0       A   1000         1
1       B   2000         2
2       C   3000         3
3       D   4000         4

In [87]:
# crate a new column revenue=price*quantity
df8["revenue"]=df8["price"]*df8["quantity"]
df8

  product  price  quantity  revenue
0       A   1000         1     1000
1       B   2000         2     4000
2       C   3000         3     9000
3       D   4000         4    16000

In [88]:
df8["revenue"].sum()

np.int64(30000)

In [89]:
# incerease all price by 10%
df8["increase_price"]=df8["price"]+df8["price"].apply(lambda x:x*0.10)
df8

  product  price  quantity  revenue  increase_price
0       A   1000         1     1000          1100.0
1       B   2000         2     4000          2200.0
2       C   3000         3     9000          3300.0
3       D   4000         4    16000          4400.0

In [90]:
# discounted price
df8["discount"]=df8["price"]-df8["price"]*0.10
df8

  product  price  quantity  revenue  increase_price  discount
0       A   1000         1     1000          1100.0     900.0
1       B   2000         2     4000          2200.0    1800.0
2       C   3000         3     9000          3300.0    2700.0
3       D   4000         4    16000          4400.0    3600.0

In [91]:
# final integrated question
# q15mini data cleaning and analysis task
data6 = {
    "customer": ["Aman", "Priya", "Rahul", "Sneha", "Karan", "Priya", "Aman"],
    "age": [25, np.nan, 30, 28, np.nan, np.nan, 25],
    "city": ["Delhi", "Mumbai", np.nan, "Ahmedabad", "Surat", "Mumbai", "Delhi"],
    "price": [1000, 1500, 2000, 1200, 1800, 1500, 1000],
    "quantity": [2, 1, 3, 2, 1, 1, 2]
}

df9 = pd.DataFrame(data6)

print(df9)

  customer   age       city  price  quantity
0     Aman  25.0      Delhi   1000         2
1    Priya   NaN     Mumbai   1500         1
2    Rahul  30.0        NaN   2000         3
3    Sneha  28.0  Ahmedabad   1200         2
4    Karan   NaN      Surat   1800         1
5    Priya   NaN     Mumbai   1500         1
6     Aman  25.0      Delhi   1000         2

In [92]:
df9

  customer   age       city  price  quantity
0     Aman  25.0      Delhi   1000         2
1    Priya   NaN     Mumbai   1500         1
2    Rahul  30.0        NaN   2000         3
3    Sneha  28.0  Ahmedabad   1200         2
4    Karan   NaN      Surat   1800         1
5    Priya   NaN     Mumbai   1500         1
6     Aman  25.0      Delhi   1000         2

In [93]:
df9["age"]=df9["age"].fillna(df9["age"].mean())
df9

  customer   age       city  price  quantity
0     Aman  25.0      Delhi   1000         2
1    Priya  27.0     Mumbai   1500         1
2    Rahul  30.0        NaN   2000         3
3    Sneha  28.0  Ahmedabad   1200         2
4    Karan  27.0      Surat   1800         1
5    Priya  27.0     Mumbai   1500         1
6     Aman  25.0      Delhi   1000         2

In [94]:
df9["city"]=df9["city"].fillna("Unknow")
df9

  customer   age       city  price  quantity
0     Aman  25.0      Delhi   1000         2
1    Priya  27.0     Mumbai   1500         1
2    Rahul  30.0     Unknow   2000         3
3    Sneha  28.0  Ahmedabad   1200         2
4    Karan  27.0      Surat   1800         1
5    Priya  27.0     Mumbai   1500         1
6     Aman  25.0      Delhi   1000         2

In [95]:
new_df9=df9.drop_duplicates()
new_df9

  customer   age       city  price  quantity
0     Aman  25.0      Delhi   1000         2
1    Priya  27.0     Mumbai   1500         1
2    Rahul  30.0     Unknow   2000         3
3    Sneha  28.0  Ahmedabad   1200         2
4    Karan  27.0      Surat   1800         1

In [96]:
new_df9["revenue"]=new_df9["price"]*new_df9["quantity"]
new_df9

  customer   age       city  price  quantity  revenue
0     Aman  25.0      Delhi   1000         2     2000
1    Priya  27.0     Mumbai   1500         1     1500
2    Rahul  30.0     Unknow   2000         3     6000
3    Sneha  28.0  Ahmedabad   1200         2     2400
4    Karan  27.0      Surat   1800         1     1800

In [97]:
# filter rows
less500=new_df9[new_df9["revenue"]>1500]
less500

  customer   age       city  price  quantity  revenue
0     Aman  25.0      Delhi   1000         2     2000
2    Rahul  30.0     Unknow   2000         3     6000
3    Sneha  28.0  Ahmedabad   1200         2     2400
4    Karan  27.0      Surat   1800         1     1800

In [98]:
new_df9["revenue"].sort_values(ascending=False)

2    6000
3    2400
0    2000
4    1800
1    1500
Name: revenue, dtype: int64

In [99]:
new_df9.reset_index(drop=True)

  customer   age       city  price  quantity  revenue
0     Aman  25.0      Delhi   1000         2     2000
1    Priya  27.0     Mumbai   1500         1     1500
2    Rahul  30.0     Unknow   2000         3     6000
3    Sneha  28.0  Ahmedabad   1200         2     2400
4    Karan  27.0      Surat   1800         1     1800

In [100]:
q1=new_df9["revenue"].quantile(0.25)
q3=new_df9["revenue"].quantile(0.75)

iqr1=q3-q1
lower1=q1-1.5*iqr1
upper1=q3+1.5*iqr1

outliers1=new_df9[(new_df9["revenue"]<lower1)|(new_df9["revenue"]>upper1)]
q1,q3,iqr1,lower1,upper1,outliers1

(np.float64(1800.0),
 np.float64(2400.0),
 np.float64(600.0),
 np.float64(900.0),
 np.float64(3300.0),
   customer   age    city  price  quantity  revenue
 2    Rahul  30.0  Unknow   2000         3     6000)

session 10  ==merging & joining dataframe

why merging is imporatant
    in real-world scenarios,data is often stored in multiple tables/files.

    Examples:

Customer Table:

| Customer_ID | Name |
|-------------|------|
| 1 | Aman |
| 2 | Priya |

Sales Table:

| Customer_ID | Amount |
|-------------|--------|
| 1 | 500 |
| 2 | 700 |
    
to analyze data properly,we need to combine these tables.
__________________________________________
solution:
pandas provides: merge()
____________________________________________
key concept:
merge is similar to sql join

merge () function:
syntax:pd.merge(left_df,right_df,how="type",on="column")
___________________________________________
parameters:
left df=first dataframe
right df=second dataframe

how=type of join
    #inner=common values only
    #left=all values from left
    #right=all values from right
    #outer=all values from both

on=column name used for joining
____________________________________________
use case:
>combine customer data with sales
>combine dataset from munltiple sources

In [101]:
customers=pd.DataFrame({
    "customer_ID":[1,2,3],
    "name":["aman","priya","rahul"]
})

salse=pd.DataFrame({
    "customer_ID":[1,2,4],
    "amount":[500,700,300]
})

customers,salse

(   customer_ID   name
 0            1   aman
 1            2  priya
 2            3  rahul,
    customer_ID  amount
 0            1     500
 1            2     700
 2            4     300)

In [102]:
# 1.inner join :keep only matching values in both tables:

pd.merge(customers,salse,how="inner",on="customer_ID")

   customer_ID   name  amount
0            1   aman     500
1            2  priya     700

In [103]:
# 2.left join:keep all  rows from left table
pd.merge(customers,salse,how="left",on="customer_ID")

   customer_ID   name  amount
0            1   aman   500.0
1            2  priya   700.0
2            3  rahul     NaN

In [104]:
# 3 right join:keep all rows from right table
pd.merge(customers,salse,how="right",on="customer_ID")

   customer_ID   name  amount
0            1   aman     500
1            2  priya     700
2            4    NaN     300

In [105]:
# outer join:keeps all rows from both tables.
pd.merge(customers,salse,how="outer",on="customer_ID")

   customer_ID   name  amount
0            1   aman   500.0
1            2  priya   700.0
2            3  rahul     NaN
3            4    NaN   300.0

merge on multiple columns:
syntax:pd.merge(df1,df2,on=["col1","col2"])
________________________________________________
use case:
when one column is not enough to uniquely indentify data.

In [106]:
df10=pd.DataFrame({
    "id":[1,1,2],
    "city":["delhi","mumbai","delhi"],
    "sales":[100,200,300]
})

df11=pd.DataFrame({
    "id":[1,2],
    "city":["delhi","delhi"],
    "target":[150,350]
})
pd.merge(df10,df11,on=["id","city"])

   id   city  sales  target
0   1  delhi    100     150
1   2  delhi    300     350

default behavior of pd.merge()
when you do:
pd.merge(df1,df2,on["id","city"])
and do not specify how
___________________________________________
defautlt join type
the default join is:
inner join
_________________________________________
what is inner join?
it keeps only those rows where:
#values match in both dataframes
#based on the given key(s)
________________________________________
important rule
if no match exists=row is dropped
________________________________________
syntax reminder
pd.merge(df1,df2,how="inner",on=["id","city"])
is same as
pd.merge(df1,df2,on=["id","city"])
____________________________________________
demo-customer+sales merge
goal:
combine customer details with sales data.

In [107]:
merged_df=pd.merge(customers,salse,how="left",on="customer_ID")
merged_df

   customer_ID   name  amount
0            1   aman   500.0
1            2  priya   700.0
2            3  rahul     NaN

In [108]:
# q1
# create 2 dataset
df12=pd.DataFrame({
    "id":[1,2,3],
    "name":["aman","priya","rahul"]
    })

df13=pd.DataFrame({
    "id":[2,3,4],
    "score":[80,90,70]
    })
df12,df13

(   id   name
 0   1   aman
 1   2  priya
 2   3  rahul,
    id  score
 0   2     80
 1   3     90
 2   4     70)

In [109]:
# task
# 1
pd.merge(df12,df13,on="id")

   id   name  score
0   2  priya     80
1   3  rahul     90

In [110]:
# 3
pd.merge(df12,df13,on="id").count()

id       2
name     2
score    2
dtype: int64

In [111]:
# q2=duplicate key explosion
df14=pd.DataFrame({
    "id":[1,1],
    "product":["A","B"]
})

df15=pd.DataFrame({
    "id":[1,1],
    "price":[100,200]
})

df14,df15

(   id product
 0   1       A
 1   1       B,
    id  price
 0   1    100
 1   1    200)

In [112]:
# task
# 1
pd.merge(df14,df15,how="inner",on="id")

   id product  price
0   1       A    100
1   1       A    200
2   1       B    100
3   1       B    200

In [113]:
# 2
pd.merge(df14,df15,how="inner",on="id").count()

id         4
product    4
price      4
dtype: int64

In [114]:
# q3=left join with missing values
df16=pd.DataFrame({
    "id":[1,2,3],
    "name":["aman","priya","rahul"]
})

df17=pd.DataFrame({
    "id":[1],
    "salary":[50000]
})
df16,df17

(   id   name
 0   1   aman
 1   2  priya
 2   3  rahul,
    id  salary
 0   1   50000)

In [115]:
# task
# 1
left_join=pd.merge(df16,df17,how="left",on="id")
left_join

   id   name   salary
0   1   aman  50000.0
1   2  priya      NaN
2   3  rahul      NaN

In [116]:
left_join.isna()

      id   name  salary
0  False  False   False
1  False  False    True
2  False  False    True

In [117]:
left_join["salary"]=left_join["salary"].fillna(0)
left_join

   id   name   salary
0   1   aman  50000.0
1   2  priya      0.0
2   3  rahul      0.0

In [118]:
# q4=multiple key merge trap
df18=pd.DataFrame({
    "id":[1,1],
    "city":["delhi","mumbai"],
    "sales":[100,200]
})
df19=pd.DataFrame({
    "id":[1],
    "city":["delhi"],
    "target":[150]
})
df18,df19

(   id    city  sales
 0   1   delhi    100
 1   1  mumbai    200,
    id   city  target
 0   1  delhi     150)

In [119]:
# task
# 1
pd.merge(df18,df19,on="id")

   id  city_x  sales city_y  target
0   1   delhi    100  delhi     150
1   1  mumbai    200  delhi     150

In [120]:
# 2
pd.merge(df18,df19,on="id")

   id  city_x  sales city_y  target
0   1   delhi    100  delhi     150
1   1  mumbai    200  delhi     150

In [121]:
# q5=real-world merge scenario
df20=pd.DataFrame({
    "customer_id":[1,2,3],
    "name":["aman","priya","rahul"]
})
df21=pd.DataFrame({
    "customer_id":[1,1,2],
    "order_amount":[500,700,300]
    })
df20,df21

(   customer_id   name
 0            1   aman
 1            2  priya
 2            3  rahul,
    customer_id  order_amount
 0            1           500
 1            1           700
 2            2           300)

In [122]:
# task
# 1
pd.merge(df20,df21,on="customer_id")

   customer_id   name  order_amount
0            1   aman           500
1            1   aman           700
2            2  priya           300

In [123]:
# 2 clacu;ate total order amount per customers
both=pd.merge(df20,df21,on="customer_id")
both

   customer_id   name  order_amount
0            1   aman           500
1            1   aman           700
2            2  priya           300

In [124]:
total=both.groupby("name")["order_amount"].sum().reset_index()
total

    name  order_amount
0   aman          1200
1  priya           300

In [125]:
# 3 identify customer with nom orders
merged1 = pd.merge(df20, df21, on="customer_id", how="left")
print(merged1)

   customer_id   name  order_amount
0            1   aman         500.0
1            1   aman         700.0
2            2  priya         300.0
3            3  rahul           NaN

In [126]:
# find customer with no orders
no_orders=merged1[merged1["order_amount"].isna()]
no_orders

   customer_id   name  order_amount
3            3  rahul           NaN

In [127]:
# 4 missing value with 0
merged1["order_amount"]=merged1["order_amount"].fillna(0)
merged1

   customer_id   name  order_amount
0            1   aman         500.0
1            1   aman         700.0
2            2  priya         300.0
3            3  rahul           0.0

>session=11--concatenation & data reshaping
why concatenation is needed 
    some time data is split across multiple files:
    example:
        1.january sales
        2.february sales
        3.march sales

        we need to combine them into one dataset

solution:pd.concat()
>>syntax::pd.concat([df1,df2],axis=0)

>>parameters::
axis:0->row-wise(default)
    :1->coulmn wise

ignor index::True-->reset index


use case::
>combine dataset
>append row
>merge coliumn

In [128]:
df22=pd.DataFrame({"sales":[100,200]})
df23=pd.DataFrame({"sales":[300,400]})

pd.concat([df22,df23])

   sales
0    100
1    200
0    300
1    400

In [129]:
# column wise
df22=pd.DataFrame({"sales":[100,200]})
df23=pd.DataFrame({"sales":[300,400]})

pd.concat([df22,df23],axis=1)

   sales  sales
0    100    300
1    200    400

>>>pivot::
reshape data from long formate to wide formate

syntax::df.pivot(index,column,values)

In [130]:
data7={"month":["feb","feb","jan","jan"],
       "product":["A","B","A","B"],
       "sales":[100,200,150,250]}
df24=pd.DataFrame(data7)

df24.pivot(index="month",columns="product",values="sales")

product    A    B
month
feb      100  200
jan      150  250

>>>pivot table
    similar to pivot but support aggregation.

syntax::df.pivot_table(index,columns,values,aggfunc)

In [131]:
df24.pivot_table(index="month",columns="product",values="sales",aggfunc="sum")

product    A    B
month
feb      100  200
jan      150  250

>>pivot:
what problem dose pivot solve??
sometimes data is stored in long formate.
month|product|sales
jan  |A      |100
jan  |B      |200


month|product|sales
jan  |A      |150
jan  |B      |250

this called long,/tidy formate

what do we want?
we want somthing like?
month | A | B
jan   |100|200
feb   |150|250

this called wide formate

what pivpt does
pivot reaarange data:
rows->become index
unique column values->become new column
values->fill the table

In [132]:
# core idea
# pivot="eeshap table"

data8={
    "month":["jan","jan","feb","feb","mar","mar"],
    "product":["A","B","A","B","A","B"],
    "sales":[100,200,150,250,300,400]
    }
df25=pd.DataFrame(data8)
df25

  month product  sales
0   jan       A    100
1   jan       B    200
2   feb       A    150
3   feb       B    250
4   mar       A    300
5   mar       B    400

step by-step pivot explanation
we want:
#month->rows
#product->column
#sales->values

syntax:
df.pivot(index="month",column="product",values="sales")

parameter meaning:
index:what becomes rows
column:what becomes column
values:what fill the taqble

In [133]:
pivot_df=df25.pivot(index="month",columns="product",values="sales")
pivot_df

product    A    B
month
feb      150  250
jan      100  200
mar      300  400

how it worked

for each combination:
month+product->values is picked from sales

Example:
month=jan,product=A->100
month=jan,product=B->200

important rule(very inportant)
pivot works only when:

each(index,column)pair has one values
is duplicates exies->error

In [134]:
# this only for understanding if we have duplicates row
data9={
    "month":["jan","jan"],
    "product":["A","A"],
    "sales":[100,150]
    }
df26=pd.DataFrame(data9)
df26.pivot(index="month",columns="product",values="sales")

ValueError: Index contains duplicate entries, cannot reshape

why pivot fails here?

because:
month=jan ,product=A has two values:
100 and 150
  .pivot does not know wich one to choose

solution:
use pivot_table()insted

In [ ]:
df26.pivot_table(index="month",columns="product",values="sales",aggfunc="sum")

product    A
month
jan      250

pivot vs pivot table

feature                 pivot       pivot_table
handels ducplicate      no          yes
aggregation             no          yes
default aggfun          no          mean


default parameters(importtant):
pivot():
df.pivot(index=none,column=none,values=none)
no default are useful->you must specify all 3
______________________________________________________
pivot_table():
df.pivot_table(index=none,column=none,values=none,aggfun="mean")
default aggregation=mean

real-world use case:
imagine:
you have sales data like:
date|product|sales
and you want:
date-wise report:
date|A|B|C

use pivot()
____________________________________________________
where it is used:
1.bussiness report
2.dashboard creation
3.excel-like summaries
4.data reshaping before ML




>demo-combine monthly sales:
goal:
combine multiple monthly sales dataset.

In [ ]:
jan=pd.DataFrame({"sales":[100,200]})
feb=pd.DataFrame({"sales":[150,250]})

combined=pd.concat([jan,feb],ignore_index=True)
combined

   sales
0    100
1    200
2    150
3    250

In [ ]:
# basic merge practice:
# q1:
# create two dataframes
cust=pd.DataFrame({"cust_id":[1,2,3],"name":["aman","priya","rahul"]})
ord=pd.DataFrame({"cust_id":[1,2,4],"amount":[500,700,300]})
inner_merge=pd.merge(cust,ord,how="inner",on="cust_id")
left_merge=pd.merge(cust,ord,how="left",on="cust_id")
outer_merge=pd.merge(cust,ord,how="outer",on="cust_id")

print("inner:\n",inner_merge)
print("\nleft:\n",left_merge)
print("\nouter:\n",outer_merge)
# inner_merge,left_merge,outer_merge

inner:
    cust_id   name  amount
0        1   aman     500
1        2  priya     700

left:
    cust_id   name  amount
0        1   aman   500.0
1        2  priya   700.0
2        3  rahul     NaN

outer:
    cust_id   name  amount
0        1   aman   500.0
1        2  priya   700.0
2        3  rahul     NaN
3        4    NaN   300.0

In [ ]:
# q2:merge and analyze
print("\nleft:\n",left_merge)
print("\nwith missing values:\n",left_merge[left_merge["amount"].isna()])

left:
    cust_id   name  amount
0        1   aman   500.0
1        2  priya   700.0
2        3  rahul     0.0

with missing values:
 Empty DataFrame
Columns: [cust_id, name, amount]
Index: []

In [ ]:
left_merge["amount"]=left_merge["amount"].fillna(0)
left_merge

   cust_id   name  amount
0        1   aman   500.0
1        2  priya   700.0
2        3  rahul     0.0

In [ ]:
ord.groupby("cust_id")["amount"].sum().reset_index()

   cust_id  amount
0        1     500
1        2     700
2        4     300

In [ ]:
# q3
df27=pd.DataFrame({"id":[1,1,2],
                   "city":["delhi","mumbai","delhi"],
                   "sales":[100,200,300]})

df28=pd.DataFrame({"id":[1,2],
                   "city":["delhi","delhi"],
                   "target":[150,350]})
merge_id=pd.merge(df27,df28,on="id")
merge_id_city=pd.merge(df27,df28,on=["id","city"])

merge_id,merge_id_city

(   id  city_x  sales city_y  target
 0   1   delhi    100  delhi     150
 1   1  mumbai    200  delhi     150
 2   2   delhi    300  delhi     350,
    id   city  sales  target
 0   1  delhi    100     150
 1   2  delhi    300     350)

In [ ]:
# q4
df29=pd.DataFrame({"id":[1,1],"product":["A","B"]})
df30=pd.DataFrame({"id":[1,1],"price":[100,200]})

inner_merge=pd.merge(df29,df30,how="inner",on="id")
count=inner_merge.count()
inner_merge,inner_merge.count(),inner_merge.shape

(   id product  price
 0   1       A    100
 1   1       A    200
 2   1       B    100
 3   1       B    200,
 id         4
 product    4
 price      4
 dtype: int64,
 (4, 3))

In [ ]:
# q5
df31=pd.DataFrame({"sales":[100,200]})
df32=pd.DataFrame({"sales":[300,400]})

concat_row=pd.concat([df31,df32],axis=0)
using_ignor_index=pd.concat([df31,df32],axis=0,ignore_index=True)
concat_row,using_ignor_index

(   sales
 0    100
 1    200
 0    300
 1    400,
    sales
 0    100
 1    200
 2    300
 3    400)

In [ ]:
# q6
df33=pd.DataFrame({"A":[1,2]})
df34=pd.DataFrame({"B":[3,4]})

concat_column=pd.concat([df33,df34],axis=1)
concat_column

   A  B
0  1  3
1  2  4

In [ ]:
# q7
df35=pd.DataFrame({"jan":[100,200]})
df36=pd.DataFrame({"feb":[150,250]})
df37=pd.DataFrame({"mar":[300,350]})

pd.concat([df35,df36,df37],ignore_index=True)

     jan    feb    mar
0  100.0    NaN    NaN
1  200.0    NaN    NaN
2    NaN  150.0    NaN
3    NaN  250.0    NaN
4    NaN    NaN  300.0
5    NaN    NaN  350.0

In [ ]:
# q8
df38=pd.DataFrame({"month":["jan","jan","feb","feb"],
              "product":["A","B","A","B"],
              "sales":[100,200,150,250]})

pivot1=pd.pivot(df38,index="month",columns="product",values="sales")
pivot1

product    A    B
month
feb      150  250
jan      100  200

In [ ]:
# q9
pivot_table1=pd.pivot_table(df38,index="month",columns="product",values="sales",aggfunc="sum")
pivot_table1

product    A    B
month
feb      150  250
jan      100  200

In [ ]:
# q10
customers1=pd.DataFrame({"id":[1,2,3],
                   "name":["aman","priya","rahul"]})

salse1=pd.DataFrame({"id":[1,1,2],
                     "product":["A","B","A"],
                     "amount":[100,200,300]})

merge_customers11=pd.merge(customers1,salse1,how="outer",on="id")
missing_with_0=merge_customers11.fillna(0)
pivot_table2=pd.pivot_table(missing_with_0,index="name",columns="product",values="amount")
pivot_table2_with_0=pivot_table2.fillna(0)
merge_customers11,missing_with_0,pivot_table2,pivot_table2_with_0

(   id   name product  amount
 0   1   aman       A   100.0
 1   1   aman       B   200.0
 2   2  priya       A   300.0
 3   3  rahul     NaN     NaN,
    id   name product  amount
 0   1   aman       A   100.0
 1   1   aman       B   200.0
 2   2  priya       A   300.0
 3   3  rahul       0     0.0,
 product    0      A      B
 name
 aman     NaN  100.0  200.0
 priya    NaN  300.0    NaN
 rahul    0.0    NaN    NaN,
 product    0      A      B
 name
 aman     0.0  100.0  200.0
 priya    0.0  300.0    0.0
 rahul    0.0    0.0    0.0)

# SESSION 12 — GroupBy & Aggregations in Pandas

## Why GroupBy is Important

In real-world data analysis, we often need to answer questions like:

• Total revenue per region  
• Average salary per department  
• Maximum sales per product  

This requires:

-  Grouping data  
-  Applying calculations  

---

# What is GroupBy?

GroupBy means:

-  Split data into groups  
-  Apply a function  
-  Combine results  

---

# Real-Life Analogy

Think of:

Class of students → grouped by section

Then:

• Calculate average marks per section  
• Find top student per section  

---

# One-Line Definition

GroupBy = Split + Apply + Combine


# Basic Syntax

df.groupby("column")


# Important

groupby() does NOT compute anything immediately

It creates a grouped object.

You must apply functions like:

• sum()  
• mean()  
• count()  
• max()  
• min()

In [ ]:
import pandas as pd
df39=pd.DataFrame({"region":["north","south","north","south","east"],
                   "category":["A","A","B","B","A"],
                   "revenue":[100,200,150,250,300]})
df39

  region category  revenue
0  north        A      100
1  south        A      200
2  north        B      150
3  south        B      250
4   east        A      300

In [ ]:
# ex 1 -group by one cloumn
 
# group data by region
df39.groupby("region").sum()

       category  revenue
region
east          A      300
north        AB      250
south        AB      450

# Parameters of groupby()

df.groupby(by, axis=0, level=None, as_index=True, sort=True, group_keys=True, observed=False, dropna=True)

---

# Parameter Explanation

1. by  
Column name(s) used for grouping  

Example:
"groupby('Region')"

---

2. axis (default = 0)  
0 → group rows  
1 → group columns  

---

3. level  
Used with MultiIndex (advanced)

---

4. as_index (default = True)

True → group column becomes index  
False → group column remains normal column  

---

5. sort (default = True)

True → sort group keys  
False → keep original order  

---

6. group_keys (default = True)

Controls whether group labels appear in output

---

7. observed (default = False)

Used with categorical data

---

8. dropna (default = True)

Drop missing group keys

In [ ]:
# as_index=false example

df39.groupby("region",as_index=False).sum()

  region category  revenue
0   east        A      300
1  north       AB      250
2  south       AB      450

In [ ]:
# ex 2 ==group by multiple column
# group by region and category
df39.groupby(["region","category"]).sum

                 revenue
region category
east   A             300
north  A             100
       B             150
south  A             200
       B             250

# Aggregation Functions

Common functions:

• sum()  
• mean()  
• count()  
• max()  
• min()  
• std()

---

# Example

In [ ]:
df39.groupby("region")["revenue"].mean()

region
east     300.0
north    125.0
south    225.0
Name: revenue, dtype: float64

# agg() Function

Allows multiple aggregations

---

# Syntax

df.groupby("column").agg(function)

---

# Example

In [ ]:
df39.groupby("region").agg({"revenue":"sum"})

        revenue
region
east        300
north       250
south       450

In [ ]:
# multiple aggregation
# we can apply multiple function
df39.groupby("region").agg({"revenue":["sum","mean","max"]})

       revenue
           sum   mean  max
region
east       300  300.0  300
north      250  125.0  150
south      450  225.0  250

In [ ]:
# rename aggregation output
# using named aggregations
df39.groupby("region").agg(total_revenue=("revenue","sum"),
                           avg_revenue=("revenue","mean"))

        total_revenue  avg_revenue
region
east              300        300.0
north             250        125.0
south             450        225.0

In [ ]:
# revenue by region & category
# goal:find total revenue grouped by region and category
df39.groupby(["region","category"])["revenue"].sum()

region  category
east    A           300
north   A           100
        B           150
south   A           200
        B           250
Name: revenue, dtype: int64

In [ ]:
# reset index (important step)
# after grouping,index becomes hierarchical
# use: reset_index()
# result = df.groupby(["Region","Category"])["Revenue"].sum()
result = df39.groupby(["region","category"])["revenue"].sum().reset_index()

result

  region category  revenue
0   east        A      300
1  north        A      100
2  north        B      150
3  south        A      200
4  south        B      250

# Real-World Use Cases

• Sales analysis by region  
• Customer segmentation  
• Product performance  
• Financial reporting  

---

# Common Mistakes

• Forgetting aggregation after groupby  
• Confusion with multi-index  
• Not using reset_index()  


# Summary

GroupBy → grouping data  

Aggregation → applying functions  

agg() → multiple calculations  

Multi-group → more granular analysis  

---

# Key Insight

GroupBy is the backbone of data analytics in Pandas

In [140]:
# practice set of groupby andd agg function
# q1
df40=pd.DataFrame({"Region":["North","South","North","East"],
                "Revenue" : [100, 200, 150, 300]
                })
df40

  Region  Revenue
0  North      100
1  South      200
2  North      150
3   East      300

In [143]:
df40.groupby("Region").sum()

        Revenue
Region
East        300
North       250
South       200

In [146]:
df40["Revenue"].sum()

np.int64(750)

In [148]:
# q2
df40.groupby("Region")["Revenue"].mean()

Region
East     300.0
North    125.0
South    200.0
Name: Revenue, dtype: float64

In [ ]:
# q3
df41=pd.DataFrame({"category":["A","A","B","B","A"],
                   "revenue":[100,200,150,250,300]})

df41

  category  revenue
0        A      100
1        A      200
2        B      150
3        B      250
4        A      300

In [150]:
df41.groupby("category").sum()

          revenue
category
A             600
B             400

In [151]:
df41["revenue"].sum()

np.int64(1000)

In [156]:
#= q4
df41.groupby("category")["revenue"].max()

category
A    300
B    250
Name: revenue, dtype: int64

In [157]:
#= q4
df41.groupby("category")["revenue"].min()

category
A    100
B    150
Name: revenue, dtype: int64

In [ ]:
# q5
df42=pd.DataFrame({"region":["north","south","north","south","east"],
                   "revenue":[100,200,150,250,300]})
df42

  region  revenue
0  north      100
1  south      200
2  north      150
3  south      250
4   east      300

In [159]:
df42.groupby("region").count()

        revenue
region
east          1
north         2
south         2

In [160]:
# q6
df43=pd.DataFrame({"Region":["North","South","North","East"],  
"Category":["A","A","B","B"],  
"Revenue":[100,200,150,300]})

df43

  Region Category  Revenue
0  North        A      100
1  South        A      200
2  North        B      150
3   East        B      300

In [161]:
df43.groupby(["Region","Category"]).sum()

                 Revenue
Region Category
East   B             300
North  A             100
       B             150
South  A             200

In [162]:
df43["Revenue"].sum()

np.int64(750)

In [163]:
# q7
df43.groupby("Region")["Revenue"].mean()

Region
East     300.0
North    125.0
South    200.0
Name: Revenue, dtype: float64

In [165]:
# Q8
df40.groupby("Region",as_index=False).sum()

  Region  Revenue
0   East      300
1  North      250
2  South      200

In [167]:
# q9
df40.groupby("Region")["Revenue"].sum().sort_values(ascending=False)

Region
East     300
North    250
South    200
Name: Revenue, dtype: int64

In [171]:
# q10
df42.groupby("region").agg(["sum","mean"])

       revenue
           sum   mean
region
east       300  300.0
north      250  125.0
south      450  225.0

In [172]:
# q11
df42.groupby("region").agg(
    total_revenue=("revenue","sum"),
    avg_revenue=("revenue","mean")
)

        total_revenue  avg_revenue
region
east              300        300.0
north             250        125.0
south             450        225.0

In [173]:
# q12
df43.groupby(["Region","Category"]).sum()

                 Revenue
Region Category
East   B             300
North  A             100
       B             150
South  A             200

In [176]:
df43["Revenue"].sum()

np.int64(750)

In [178]:
df43.groupby(["Region","Category"]).sum().reset_index()

  Region Category  Revenue
0   East        B      300
1  North        A      100
2  North        B      150
3  South        A      200

In [180]:
# q13
df43.groupby("Region")["Revenue"].count()

Region
East     1
North    2
South    1
Name: Revenue, dtype: int64

In [ ]:
# q14
df43.groupby("Region")["Revenue"].std()

Region
East           NaN
North    35.355339
South          NaN
Name: Revenue, dtype: float64

In [ ]:
# q15
df42.groupby("region").sum()

        revenue
region
east        300
north       250
south       450

In [186]:
df42["revenue"].sum()

np.int64(1000)

In [187]:
df42["revenue"].mean()

np.float64(200.0)

In [188]:
df42.groupby("region")["revenue"].sum().sort_index(ascending=False)

region
south    450
north    250
east     300
Name: revenue, dtype: int64

In [189]:
df42.groupby("region")["revenue"].sum().reset_index()

  region  revenue
0   east      300
1  north      250
2  south      450