In [2]:
import pandas as pd
data={
    "region":["north","south","north","south","east"],
    "category":["a","a","b","b","a"],
    "revenue":[100,200,150,250,300]
}
df=pd.DataFrame(data)
df

  region category  revenue
0  north        a      100
1  south        a      200
2  north        b      150
3  south        b      250
4   east        a      300

In [8]:
df.groupby("region").sum()

       category  revenue
region
east          a      300
north        ab      250
south        ab      450

parameter of groupby
df.groupby(by,axis=0,level=none,as_index=True,group_keys=True,observed=False,dropna=True)
1.by=column name(s) used for grouping
ex:df.groupby("rigion").

In [25]:
df.groupby("region",as_index=False).sum()

  region category  revenue
0   east        a      300
1  north       ab      250
2  south       ab      450

In [26]:
df.groupby(["region","category"]).sum()

                 revenue
region category
east   a             300
north  a             100
       b             150
south  a             200
       b             250

>aggregation function
1.sum()
2.mean()
3.count()
4.max()
5.min()
6.std()

In [27]:
df.groupby("region")["revenue"].mean()

region
east     300.0
north    125.0
south    225.0
Name: revenue, dtype: float64

In [28]:
df.groupby("region").agg({
    "revenue":"sum"
})

        revenue
region
east        300
north       250
south       450

In [29]:
df.groupby("region").agg({
    "revenue":["sum","mean","std","min","max"]
})

       revenue
           sum   mean        std  min  max
region
east       300  300.0        NaN  300  300
north      250  125.0  35.355339  100  150
south      450  225.0  35.355339  200  250

In [30]:
df.groupby("region").agg(
    total_revenue=("revenue","sum"),
    avg_revenue=("revenue","mean")
)

        total_revenue  avg_revenue
region
east              300        300.0
north             250        125.0
south             450        225.0

In [31]:
df.groupby(["region","category"])["revenue"].sum()

region  category
east    a           300
north   a           100
        b           150
south   a           200
        b           250
Name: revenue, dtype: int64

In [32]:
df.groupby(["region","category"])["revenue"].sum().reset_index()

  region category  revenue
0   east        a      300
1  north        a      100
2  north        b      150
3  south        a      200
4  south        b      250