In [2]:
import pandas as pd
import numpy as np

# Customer dataset
customers = pd.DataFrame({
    "Customer_ID": [1,2,3,4,5,6],
    "Name": ["Aman Sharma","Priya Patel","Rahul Verma","Sneha Shah","Karan Mehta","Riya Jain"],
    "Region": ["North","South","East","West","North",None]
})

# Orders dataset
orders = pd.DataFrame({
    "Customer_ID": [1,1,2,3,4,4,5,6,6],
    "Product": ["Laptop","Mouse","Laptop","Tablet","Laptop","Tablet","Mouse","Laptop","Mouse"],
    "Category": ["Electronics","electronics","Electronics","electronics","ELECTRONICS","electronics","electronics","Electronics","electronics"],
    "Amount": [50000,2000,55000,30000,60000,25000,1500,70000,np.nan],
    "Order_Date": ["2024-01-01","2024-01-05","2024-02-01","2024-02-10","2024-03-01","2024-03-05","2024-03-10","2024-04-01","2024-04-05"]
})

customers, orders

(   Customer_ID         Name Region
 0            1  Aman Sharma  North
 1            2  Priya Patel  South
 2            3  Rahul Verma   East
 3            4   Sneha Shah   West
 4            5  Karan Mehta  North
 5            6    Riya Jain    NaN,
    Customer_ID Product     Category   Amount  Order_Date
 0            1  Laptop  Electronics  50000.0  2024-01-01
 1            1   Mouse  electronics   2000.0  2024-01-05
 2            2  Laptop  Electronics  55000.0  2024-02-01
 3            3  Tablet  electronics  30000.0  2024-02-10
 4            4  Laptop  ELECTRONICS  60000.0  2024-03-01
 5            4  Tablet  electronics  25000.0  2024-03-05
 6            5   Mouse  electronics   1500.0  2024-03-10
 7            6  Laptop  Electronics  70000.0  2024-04-01
 8            6   Mouse  electronics      NaN  2024-04-05)

In [3]:
# customer data clean
customers

   Customer_ID         Name Region
0            1  Aman Sharma  North
1            2  Priya Patel  South
2            3  Rahul Verma   East
3            4   Sneha Shah   West
4            5  Karan Mehta  North
5            6    Riya Jain    NaN

In [4]:
customers["Region"]=customers["Region"].fillna("Unknow")
customers

   Customer_ID         Name  Region
0            1  Aman Sharma   North
1            2  Priya Patel   South
2            3  Rahul Verma    East
3            4   Sneha Shah    West
4            5  Karan Mehta   North
5            6    Riya Jain  Unknow

In [5]:
# order data clean
orders

   Customer_ID Product     Category   Amount  Order_Date
0            1  Laptop  Electronics  50000.0  2024-01-01
1            1   Mouse  electronics   2000.0  2024-01-05
2            2  Laptop  Electronics  55000.0  2024-02-01
3            3  Tablet  electronics  30000.0  2024-02-10
4            4  Laptop  ELECTRONICS  60000.0  2024-03-01
5            4  Tablet  electronics  25000.0  2024-03-05
6            5   Mouse  electronics   1500.0  2024-03-10
7            6  Laptop  Electronics  70000.0  2024-04-01
8            6   Mouse  electronics      NaN  2024-04-05

In [6]:
orders["Amount"]=orders["Amount"].fillna(orders["Amount"].mean())
orders

   Customer_ID Product     Category   Amount  Order_Date
0            1  Laptop  Electronics  50000.0  2024-01-01
1            1   Mouse  electronics   2000.0  2024-01-05
2            2  Laptop  Electronics  55000.0  2024-02-01
3            3  Tablet  electronics  30000.0  2024-02-10
4            4  Laptop  ELECTRONICS  60000.0  2024-03-01
5            4  Tablet  electronics  25000.0  2024-03-05
6            5   Mouse  electronics   1500.0  2024-03-10
7            6  Laptop  Electronics  70000.0  2024-04-01
8            6   Mouse  electronics  36687.5  2024-04-05

In [7]:
orders["Category"]=orders["Category"].replace("ELECTRONICS","Electronics")
orders

   Customer_ID Product     Category   Amount  Order_Date
0            1  Laptop  Electronics  50000.0  2024-01-01
1            1   Mouse  electronics   2000.0  2024-01-05
2            2  Laptop  Electronics  55000.0  2024-02-01
3            3  Tablet  electronics  30000.0  2024-02-10
4            4  Laptop  Electronics  60000.0  2024-03-01
5            4  Tablet  electronics  25000.0  2024-03-05
6            5   Mouse  electronics   1500.0  2024-03-10
7            6  Laptop  Electronics  70000.0  2024-04-01
8            6   Mouse  electronics  36687.5  2024-04-05

In [8]:
orders["Category"]=orders["Category"].replace("electronics","Electronics")
orders

   Customer_ID Product     Category   Amount  Order_Date
0            1  Laptop  Electronics  50000.0  2024-01-01
1            1   Mouse  Electronics   2000.0  2024-01-05
2            2  Laptop  Electronics  55000.0  2024-02-01
3            3  Tablet  Electronics  30000.0  2024-02-10
4            4  Laptop  Electronics  60000.0  2024-03-01
5            4  Tablet  Electronics  25000.0  2024-03-05
6            5   Mouse  Electronics   1500.0  2024-03-10
7            6  Laptop  Electronics  70000.0  2024-04-01
8            6   Mouse  Electronics  36687.5  2024-04-05

In [9]:
orders["Order_Date"]=pd.to_datetime(orders["Order_Date"])
orders

   Customer_ID Product     Category   Amount Order_Date
0            1  Laptop  Electronics  50000.0 2024-01-01
1            1   Mouse  Electronics   2000.0 2024-01-05
2            2  Laptop  Electronics  55000.0 2024-02-01
3            3  Tablet  Electronics  30000.0 2024-02-10
4            4  Laptop  Electronics  60000.0 2024-03-01
5            4  Tablet  Electronics  25000.0 2024-03-05
6            5   Mouse  Electronics   1500.0 2024-03-10
7            6  Laptop  Electronics  70000.0 2024-04-01
8            6   Mouse  Electronics  36687.5 2024-04-05

In [15]:
merged_data=pd.merge(customers,orders,how="outer",on="Customer_ID")
merged_data

   Customer_ID         Name  Region Product     Category   Amount Order_Date
0            1  Aman Sharma   North  Laptop  Electronics  50000.0 2024-01-01
1            1  Aman Sharma   North   Mouse  Electronics   2000.0 2024-01-05
2            2  Priya Patel   South  Laptop  Electronics  55000.0 2024-02-01
3            3  Rahul Verma    East  Tablet  Electronics  30000.0 2024-02-10
4            4   Sneha Shah    West  Laptop  Electronics  60000.0 2024-03-01
5            4   Sneha Shah    West  Tablet  Electronics  25000.0 2024-03-05
6            5  Karan Mehta   North   Mouse  Electronics   1500.0 2024-03-10
7            6    Riya Jain  Unknow  Laptop  Electronics  70000.0 2024-04-01
8            6    Riya Jain  Unknow   Mouse  Electronics  36687.5 2024-04-05

In [22]:
merged_data.groupby(["Name", "Region"]).agg({
    "Category": "first",
    "Amount": "sum"
}).reset_index()

          Name  Region     Category    Amount
0  Aman Sharma   North  Electronics   52000.0
1  Karan Mehta   North  Electronics    1500.0
2  Priya Patel   South  Electronics   55000.0
3  Rahul Verma    East  Electronics   30000.0
4    Riya Jain  Unknow  Electronics  106687.5
5   Sneha Shah    West  Electronics   85000.0

In [12]:
pd.pivot_table(merged_data,
               values="Amount",
               index="Region",
               columns="Product",
               aggfunc="sum",
               fill_value=0,
               margins=True)

Product    Laptop    Mouse   Tablet       All
Region
East          0.0      0.0  30000.0   30000.0
North     50000.0   3500.0      0.0   53500.0
South     55000.0      0.0      0.0   55000.0
Unknow    70000.0  36687.5      0.0  106687.5
West      60000.0      0.0  25000.0   85000.0
All      235000.0  40187.5  55000.0  330187.5