In [2]:
import pandas as pd
import numpy as np

# Customer dataset
customers = pd.DataFrame({
    "Customer_ID": [1,2,3,4,5,6],
    "Name": ["Aman Sharma","Priya Patel","Rahul Verma","Sneha Shah","Karan Mehta","Riya Jain"],
    "Region": ["North","South","East","West","North",None]
})

# Orders dataset
orders = pd.DataFrame({
    "Customer_ID": [1,1,2,3,4,4,5,6,6],
    "Product": ["Laptop","Mouse","Laptop","Tablet","Laptop","Tablet","Mouse","Laptop","Mouse"],
    "Category": ["Electronics","electronics","Electronics","electronics","ELECTRONICS","electronics","electronics","Electronics","electronics"],
    "Amount": [50000,2000,55000,30000,60000,25000,1500,70000,np.nan],
    "Order_Date": ["2024-01-01","2024-01-05","2024-02-01","2024-02-10","2024-03-01","2024-03-05","2024-03-10","2024-04-01","2024-04-05"]
})

customers, orders

(   Customer_ID         Name Region
 0            1  Aman Sharma  North
 1            2  Priya Patel  South
 2            3  Rahul Verma   East
 3            4   Sneha Shah   West
 4            5  Karan Mehta  North
 5            6    Riya Jain    NaN,
    Customer_ID Product     Category   Amount  Order_Date
 0            1  Laptop  Electronics  50000.0  2024-01-01
 1            1   Mouse  electronics   2000.0  2024-01-05
 2            2  Laptop  Electronics  55000.0  2024-02-01
 3            3  Tablet  electronics  30000.0  2024-02-10
 4            4  Laptop  ELECTRONICS  60000.0  2024-03-01
 5            4  Tablet  electronics  25000.0  2024-03-05
 6            5   Mouse  electronics   1500.0  2024-03-10
 7            6  Laptop  Electronics  70000.0  2024-04-01
 8            6   Mouse  electronics      NaN  2024-04-05)

In [3]:
# customers describe
customers.describe()

       Customer_ID
count     6.000000
mean      3.500000
std       1.870829
min       1.000000
25%       2.250000
50%       3.500000
75%       4.750000
max       6.000000

In [4]:
# orders describe
orders.describe()

       Customer_ID        Amount
count     9.000000      8.000000
mean      3.555556  36687.500000
std       1.943651  26154.673852
min       1.000000   1500.000000
25%       2.000000  19250.000000
50%       4.000000  40000.000000
75%       5.000000  56250.000000
max       6.000000  70000.000000

In [5]:
# customer first 5 values
customers.head()

   Customer_ID         Name Region
0            1  Aman Sharma  North
1            2  Priya Patel  South
2            3  Rahul Verma   East
3            4   Sneha Shah   West
4            5  Karan Mehta  North

In [6]:
# orders first 5 val
orders.head()

   Customer_ID Product     Category   Amount  Order_Date
0            1  Laptop  Electronics  50000.0  2024-01-01
1            1   Mouse  electronics   2000.0  2024-01-05
2            2  Laptop  Electronics  55000.0  2024-02-01
3            3  Tablet  electronics  30000.0  2024-02-10
4            4  Laptop  ELECTRONICS  60000.0  2024-03-01

In [7]:
# customers last 5 val
customers.tail()

   Customer_ID         Name Region
1            2  Priya Patel  South
2            3  Rahul Verma   East
3            4   Sneha Shah   West
4            5  Karan Mehta  North
5            6    Riya Jain    NaN

In [8]:
# orders last 5 val
orders.tail()

   Customer_ID Product     Category   Amount  Order_Date
4            4  Laptop  ELECTRONICS  60000.0  2024-03-01
5            4  Tablet  electronics  25000.0  2024-03-05
6            5   Mouse  electronics   1500.0  2024-03-10
7            6  Laptop  Electronics  70000.0  2024-04-01
8            6   Mouse  electronics      NaN  2024-04-05

In [9]:
# info
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  6 non-null      int64
 1   Name         6 non-null      str
 2   Region       5 non-null      str
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [10]:
# info orders
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  9 non-null      int64
 1   Product      9 non-null      str
 2   Category     9 non-null      str
 3   Amount       8 non-null      float64
 4   Order_Date   9 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 492.0 bytes

In [11]:
# customer multiple column
customers[["Name","Region"]]

          Name Region
0  Aman Sharma  North
1  Priya Patel  South
2  Rahul Verma   East
3   Sneha Shah   West
4  Karan Mehta  North
5    Riya Jain    NaN

In [12]:
# orders multiple column
orders[["Product","Category","Order_Date"]]

  Product     Category  Order_Date
0  Laptop  Electronics  2024-01-01
1   Mouse  electronics  2024-01-05
2  Laptop  Electronics  2024-02-01
3  Tablet  electronics  2024-02-10
4  Laptop  ELECTRONICS  2024-03-01
5  Tablet  electronics  2024-03-05
6   Mouse  electronics  2024-03-10
7  Laptop  Electronics  2024-04-01
8   Mouse  electronics  2024-04-05

In [13]:
# customer with loc
print("customer second row")
customers.loc[1]

customer second row

Customer_ID              2
Name           Priya Patel
Region               South
Name: 1, dtype: object

In [14]:
print("customer row with colum one val")
customers.loc[2,"Name"]

customer row with colum one val

'Rahul Verma'

In [15]:
# orders using iloc
print("orders one val or mul val")
print("2 index of all column value")
orders.iloc[2]

orders one val or mul val
2 index of all column value

Customer_ID              2
Product             Laptop
Category       Electronics
Amount             55000.0
Order_Date      2024-02-01
Name: 2, dtype: object

In [16]:
print("index base give value")
orders.iloc[2,2]

index base give value

'Electronics'

In [17]:
merged=pd.merge(customers,orders,how="outer",on="Customer_ID")
merged

   Customer_ID         Name Region Product     Category   Amount  Order_Date
0            1  Aman Sharma  North  Laptop  Electronics  50000.0  2024-01-01
1            1  Aman Sharma  North   Mouse  electronics   2000.0  2024-01-05
2            2  Priya Patel  South  Laptop  Electronics  55000.0  2024-02-01
3            3  Rahul Verma   East  Tablet  electronics  30000.0  2024-02-10
4            4   Sneha Shah   West  Laptop  ELECTRONICS  60000.0  2024-03-01
5            4   Sneha Shah   West  Tablet  electronics  25000.0  2024-03-05
6            5  Karan Mehta  North   Mouse  electronics   1500.0  2024-03-10
7            6    Riya Jain    NaN  Laptop  Electronics  70000.0  2024-04-01
8            6    Riya Jain    NaN   Mouse  electronics      NaN  2024-04-05

In [18]:
merged.drop_duplicates()

   Customer_ID         Name Region Product     Category   Amount  Order_Date
0            1  Aman Sharma  North  Laptop  Electronics  50000.0  2024-01-01
1            1  Aman Sharma  North   Mouse  electronics   2000.0  2024-01-05
2            2  Priya Patel  South  Laptop  Electronics  55000.0  2024-02-01
3            3  Rahul Verma   East  Tablet  electronics  30000.0  2024-02-10
4            4   Sneha Shah   West  Laptop  ELECTRONICS  60000.0  2024-03-01
5            4   Sneha Shah   West  Tablet  electronics  25000.0  2024-03-05
6            5  Karan Mehta  North   Mouse  electronics   1500.0  2024-03-10
7            6    Riya Jain    NaN  Laptop  Electronics  70000.0  2024-04-01
8            6    Riya Jain    NaN   Mouse  electronics      NaN  2024-04-05

In [19]:
clean_merged=merged.replace("electronics","Electronics")
clean_merged

   Customer_ID         Name Region Product     Category   Amount  Order_Date
0            1  Aman Sharma  North  Laptop  Electronics  50000.0  2024-01-01
1            1  Aman Sharma  North   Mouse  Electronics   2000.0  2024-01-05
2            2  Priya Patel  South  Laptop  Electronics  55000.0  2024-02-01
3            3  Rahul Verma   East  Tablet  Electronics  30000.0  2024-02-10
4            4   Sneha Shah   West  Laptop  ELECTRONICS  60000.0  2024-03-01
5            4   Sneha Shah   West  Tablet  Electronics  25000.0  2024-03-05
6            5  Karan Mehta  North   Mouse  Electronics   1500.0  2024-03-10
7            6    Riya Jain    NaN  Laptop  Electronics  70000.0  2024-04-01
8            6    Riya Jain    NaN   Mouse  Electronics      NaN  2024-04-05

In [20]:
clean_merged1=clean_merged.replace("ELECTRONICS","Electronics")
clean_merged1

   Customer_ID         Name Region Product     Category   Amount  Order_Date
0            1  Aman Sharma  North  Laptop  Electronics  50000.0  2024-01-01
1            1  Aman Sharma  North   Mouse  Electronics   2000.0  2024-01-05
2            2  Priya Patel  South  Laptop  Electronics  55000.0  2024-02-01
3            3  Rahul Verma   East  Tablet  Electronics  30000.0  2024-02-10
4            4   Sneha Shah   West  Laptop  Electronics  60000.0  2024-03-01
5            4   Sneha Shah   West  Tablet  Electronics  25000.0  2024-03-05
6            5  Karan Mehta  North   Mouse  Electronics   1500.0  2024-03-10
7            6    Riya Jain    NaN  Laptop  Electronics  70000.0  2024-04-01
8            6    Riya Jain    NaN   Mouse  Electronics      NaN  2024-04-05

In [21]:
clean_merged1["Amount"]=clean_merged1["Amount"].fillna(clean_merged1["Amount"].mean())
clean_merged1

   Customer_ID         Name Region Product     Category   Amount  Order_Date
0            1  Aman Sharma  North  Laptop  Electronics  50000.0  2024-01-01
1            1  Aman Sharma  North   Mouse  Electronics   2000.0  2024-01-05
2            2  Priya Patel  South  Laptop  Electronics  55000.0  2024-02-01
3            3  Rahul Verma   East  Tablet  Electronics  30000.0  2024-02-10
4            4   Sneha Shah   West  Laptop  Electronics  60000.0  2024-03-01
5            4   Sneha Shah   West  Tablet  Electronics  25000.0  2024-03-05
6            5  Karan Mehta  North   Mouse  Electronics   1500.0  2024-03-10
7            6    Riya Jain    NaN  Laptop  Electronics  70000.0  2024-04-01
8            6    Riya Jain    NaN   Mouse  Electronics  36687.5  2024-04-05

In [22]:
clean_merged1["Region"]=clean_merged1["Region"].fillna("Unknow")
clean_merged1

   Customer_ID         Name  Region Product     Category   Amount  Order_Date
0            1  Aman Sharma   North  Laptop  Electronics  50000.0  2024-01-01
1            1  Aman Sharma   North   Mouse  Electronics   2000.0  2024-01-05
2            2  Priya Patel   South  Laptop  Electronics  55000.0  2024-02-01
3            3  Rahul Verma    East  Tablet  Electronics  30000.0  2024-02-10
4            4   Sneha Shah    West  Laptop  Electronics  60000.0  2024-03-01
5            4   Sneha Shah    West  Tablet  Electronics  25000.0  2024-03-05
6            5  Karan Mehta   North   Mouse  Electronics   1500.0  2024-03-10
7            6    Riya Jain  Unknow  Laptop  Electronics  70000.0  2024-04-01
8            6    Riya Jain  Unknow   Mouse  Electronics  36687.5  2024-04-05

In [23]:
clean_merged1["Order_Date"]=pd.to_datetime(clean_merged1["Order_Date"])
clean_merged1

   Customer_ID         Name  Region Product     Category   Amount Order_Date
0            1  Aman Sharma   North  Laptop  Electronics  50000.0 2024-01-01
1            1  Aman Sharma   North   Mouse  Electronics   2000.0 2024-01-05
2            2  Priya Patel   South  Laptop  Electronics  55000.0 2024-02-01
3            3  Rahul Verma    East  Tablet  Electronics  30000.0 2024-02-10
4            4   Sneha Shah    West  Laptop  Electronics  60000.0 2024-03-01
5            4   Sneha Shah    West  Tablet  Electronics  25000.0 2024-03-05
6            5  Karan Mehta   North   Mouse  Electronics   1500.0 2024-03-10
7            6    Riya Jain  Unknow  Laptop  Electronics  70000.0 2024-04-01
8            6    Riya Jain  Unknow   Mouse  Electronics  36687.5 2024-04-05

In [24]:
clean_merged1["Amount_Category"] = np.where(clean_merged1["Amount"] > 50000, "High", "Low")
clean_merged1

,Customer_ID,Name,Region,Product,Category,Amount,Order_Date,Amount_Category
0,1,Aman Sharma,North,Laptop,Electronics,50000.0,2024-01-01,Low
1,1,Aman Sharma,North,Mouse,Electronics,2000.0,2024-01-05,Low
2,2,Priya Patel,South,Laptop,Electronics,55000.0,2024-02-01,High
3,3,Rahul Verma,East,Tablet,Electronics,30000.0,2024-02-10,Low
4,4,Sneha Shah,West,Laptop,Electronics,60000.0,2024-03-01,High
5,4,Sneha Shah,West,Tablet,Electronics,25000.0,2024-03-05,Low
6,5,Karan Mehta,North,Mouse,Electronics,1500.0,2024-03-10,Low
7,6,Riya Jain,Unknow,Laptop,Electronics,70000.0,2024-04-01,High
8,6,Riya Jain,Unknow,Mouse,Electronics,36687.5,2024-04-05,Low

In [25]:
clean_merged1["Tax"] =clean_merged1["Amount"] * 0.18
clean_merged1["Total_Amount"] = clean_merged1["Amount"] + clean_merged1["Tax"]
clean_merged1

,Customer_ID,Name,Region,Product,Category,Amount,Order_Date,Amount_Category,Tax,Total_Amount
0,1,Aman Sharma,North,Laptop,Electronics,50000.0,2024-01-01,Low,9000.00,59000.00
1,1,Aman Sharma,North,Mouse,Electronics,2000.0,2024-01-05,Low,360.00,2360.00
2,2,Priya Patel,South,Laptop,Electronics,55000.0,2024-02-01,High,9900.00,64900.00
3,3,Rahul Verma,East,Tablet,Electronics,30000.0,2024-02-10,Low,5400.00,35400.00
4,4,Sneha Shah,West,Laptop,Electronics,60000.0,2024-03-01,High,10800.00,70800.00
5,4,Sneha Shah,West,Tablet,Electronics,25000.0,2024-03-05,Low,4500.00,29500.00
6,5,Karan Mehta,North,Mouse,Electronics,1500.0,2024-03-10,Low,270.00,1770.00
7,6,Riya Jain,Unknow,Laptop,Electronics,70000.0,2024-04-01,High,12600.00,82600.00
8,6,Riya Jain,Unknow,Mouse,Electronics,36687.5,2024-04-05,Low,6603.75,43291.25

In [26]:
clean_merged1["Order_Date"] = pd.to_datetime(clean_merged1["Order_Date"])
clean_merged1

,Customer_ID,Name,Region,Product,Category,Amount,Order_Date,Amount_Category,Tax,Total_Amount
0,1,Aman Sharma,North,Laptop,Electronics,50000.0,2024-01-01,Low,9000.00,59000.00
1,1,Aman Sharma,North,Mouse,Electronics,2000.0,2024-01-05,Low,360.00,2360.00
2,2,Priya Patel,South,Laptop,Electronics,55000.0,2024-02-01,High,9900.00,64900.00
3,3,Rahul Verma,East,Tablet,Electronics,30000.0,2024-02-10,Low,5400.00,35400.00
4,4,Sneha Shah,West,Laptop,Electronics,60000.0,2024-03-01,High,10800.00,70800.00
5,4,Sneha Shah,West,Tablet,Electronics,25000.0,2024-03-05,Low,4500.00,29500.00
6,5,Karan Mehta,North,Mouse,Electronics,1500.0,2024-03-10,Low,270.00,1770.00
7,6,Riya Jain,Unknow,Laptop,Electronics,70000.0,2024-04-01,High,12600.00,82600.00
8,6,Riya Jain,Unknow,Mouse,Electronics,36687.5,2024-04-05,Low,6603.75,43291.25

In [27]:
clean_merged1["Month"] = clean_merged1["Order_Date"].dt.month
clean_merged1

,Customer_ID,Name,Region,Product,Category,Amount,Order_Date,Amount_Category,Tax,Total_Amount,Month
0,1,Aman Sharma,North,Laptop,Electronics,50000.0,2024-01-01,Low,9000.00,59000.00,1
1,1,Aman Sharma,North,Mouse,Electronics,2000.0,2024-01-05,Low,360.00,2360.00,1
2,2,Priya Patel,South,Laptop,Electronics,55000.0,2024-02-01,High,9900.00,64900.00,2
3,3,Rahul Verma,East,Tablet,Electronics,30000.0,2024-02-10,Low,5400.00,35400.00,2
4,4,Sneha Shah,West,Laptop,Electronics,60000.0,2024-03-01,High,10800.00,70800.00,3
5,4,Sneha Shah,West,Tablet,Electronics,25000.0,2024-03-05,Low,4500.00,29500.00,3
6,5,Karan Mehta,North,Mouse,Electronics,1500.0,2024-03-10,Low,270.00,1770.00,3
7,6,Riya Jain,Unknow,Laptop,Electronics,70000.0,2024-04-01,High,12600.00,82600.00,4
8,6,Riya Jain,Unknow,Mouse,Electronics,36687.5,2024-04-05,Low,6603.75,43291.25,4

In [28]:
clean_merged1["year"] = clean_merged1["Order_Date"].dt.year
clean_merged1

,Customer_ID,Name,Region,Product,Category,Amount,Order_Date,Amount_Category,Tax,Total_Amount,Month,year
0,1,Aman Sharma,North,Laptop,Electronics,50000.0,2024-01-01,Low,9000.00,59000.00,1,2024
1,1,Aman Sharma,North,Mouse,Electronics,2000.0,2024-01-05,Low,360.00,2360.00,1,2024
2,2,Priya Patel,South,Laptop,Electronics,55000.0,2024-02-01,High,9900.00,64900.00,2,2024
3,3,Rahul Verma,East,Tablet,Electronics,30000.0,2024-02-10,Low,5400.00,35400.00,2,2024
4,4,Sneha Shah,West,Laptop,Electronics,60000.0,2024-03-01,High,10800.00,70800.00,3,2024
5,4,Sneha Shah,West,Tablet,Electronics,25000.0,2024-03-05,Low,4500.00,29500.00,3,2024
6,5,Karan Mehta,North,Mouse,Electronics,1500.0,2024-03-10,Low,270.00,1770.00,3,2024
7,6,Riya Jain,Unknow,Laptop,Electronics,70000.0,2024-04-01,High,12600.00,82600.00,4,2024
8,6,Riya Jain,Unknow,Mouse,Electronics,36687.5,2024-04-05,Low,6603.75,43291.25,4,2024

In [29]:
clean_merged1["day"] = clean_merged1["Order_Date"].dt.day
clean_merged1

,Customer_ID,Name,Region,Product,Category,Amount,Order_Date,Amount_Category,Tax,Total_Amount,Month,year,day
0,1,Aman Sharma,North,Laptop,Electronics,50000.0,2024-01-01,Low,9000.00,59000.00,1,2024,1
1,1,Aman Sharma,North,Mouse,Electronics,2000.0,2024-01-05,Low,360.00,2360.00,1,2024,5
2,2,Priya Patel,South,Laptop,Electronics,55000.0,2024-02-01,High,9900.00,64900.00,2,2024,1
3,3,Rahul Verma,East,Tablet,Electronics,30000.0,2024-02-10,Low,5400.00,35400.00,2,2024,10
4,4,Sneha Shah,West,Laptop,Electronics,60000.0,2024-03-01,High,10800.00,70800.00,3,2024,1
5,4,Sneha Shah,West,Tablet,Electronics,25000.0,2024-03-05,Low,4500.00,29500.00,3,2024,5
6,5,Karan Mehta,North,Mouse,Electronics,1500.0,2024-03-10,Low,270.00,1770.00,3,2024,10
7,6,Riya Jain,Unknow,Laptop,Electronics,70000.0,2024-04-01,High,12600.00,82600.00,4,2024,1
8,6,Riya Jain,Unknow,Mouse,Electronics,36687.5,2024-04-05,Low,6603.75,43291.25,4,2024,5

In [30]:
# total sales per customers
clean_merged1.groupby("Name")["Amount"].sum()

Name
Aman Sharma     52000.0
Karan Mehta      1500.0
Priya Patel     55000.0
Rahul Verma     30000.0
Riya Jain      106687.5
Sneha Shah      85000.0
Name: Amount, dtype: float64

In [31]:
# sales per rigion
clean_merged1.groupby("Region")["Amount"].sum()

Region
East       30000.0
North      53500.0
South      55000.0
Unknow    106687.5
West       85000.0
Name: Amount, dtype: float64

In [32]:
# select per product
clean_merged1.groupby("Product")["Amount"].sum()

Product
Laptop    235000.0
Mouse      40187.5
Tablet     55000.0
Name: Amount, dtype: float64

In [33]:
# region+product
clean_merged1.groupby(["Region","Product"])["Amount"].sum().reset_index()

   Region Product   Amount
0    East  Tablet  30000.0
1   North  Laptop  50000.0
2   North   Mouse   3500.0
3   South  Laptop  55000.0
4  Unknow  Laptop  70000.0
5  Unknow   Mouse  36687.5
6    West  Laptop  60000.0
7    West  Tablet  25000.0

In [34]:
# pivot  table
pivot1=pd.pivot_table(clean_merged1,values="Amount",index="Region",columns="Product",aggfunc="sum",fill_value=0)
pivot1

Product   Laptop    Mouse   Tablet
Region
East         0.0      0.0  30000.0
North    50000.0   3500.0      0.0
South    55000.0      0.0      0.0
Unknow   70000.0  36687.5      0.0
West     60000.0      0.0  25000.0

In [35]:
# pivot  table
pivot2=pd.pivot_table(clean_merged1,values="Amount",index="Region",columns="Product",aggfunc="sum",fill_value=0)
pivot2

Product   Laptop    Mouse   Tablet
Region
East         0.0      0.0  30000.0
North    50000.0   3500.0      0.0
South    55000.0      0.0      0.0
Unknow   70000.0  36687.5      0.0
West     60000.0      0.0  25000.0

In [36]:
pivot2 = pd.pivot_table(
    clean_merged1,
    values="Amount",
    index="Month",
    columns="Product",
    aggfunc="sum",
    fill_value=0
)

pivot2

Product   Laptop    Mouse   Tablet
Month
1        50000.0   2000.0      0.0
2        55000.0      0.0  30000.0
3        60000.0   1500.0  25000.0
4        70000.0  36687.5      0.0