In [2]:
import pandas as pd

data = {
    "Customer_ID": [101,102,103,104,105,106,107,108,109,110,111],
    "Customer_Name": ["rahul","Pooja","AMIT","Neha","rahul",None,"Ravi","Sneha","Kiran","pooja","Amit"],
    "Region": ["North","south","East","West","North","South",None,"East","West","South","East"],
    "Product": ["shoes","Shirt","Shoes","Watch","shoes","Bag","Shoes",None,"Watch","Shirt","Shoes"],
    "Category": ["Fashion","fashion","FASHION","Accessories","Fashion","Accessories","Fashion","Fashion",None,"fashion","FASHION"],
    "Amount": [2500,1500,3000,2000,2500,1800,2200,2700,2100,None,3000],
    "Order_Date": ["2024-01-05","2024-01-06","2024-01-07","2024-01-08","2024-01-05",
                   "2024-01-09","2024-01-10","2024-01-11","2024-01-12","2024-01-13","2024-01-07"]
}

df = pd.DataFrame(data)

print(df)

    Customer_ID Customer_Name Region Product     Category  Amount  Order_Date
0           101         rahul  North   shoes      Fashion  2500.0  2024-01-05
1           102         Pooja  south   Shirt      fashion  1500.0  2024-01-06
2           103          AMIT   East   Shoes      FASHION  3000.0  2024-01-07
3           104          Neha   West   Watch  Accessories  2000.0  2024-01-08
4           105         rahul  North   shoes      Fashion  2500.0  2024-01-05
5           106           NaN  South     Bag  Accessories  1800.0  2024-01-09
6           107          Ravi    NaN   Shoes      Fashion  2200.0  2024-01-10
7           108         Sneha   East     NaN      Fashion  2700.0  2024-01-11
8           109         Kiran   West   Watch          NaN  2100.0  2024-01-12
9           110         pooja  South   Shirt      fashion     NaN  2024-01-13
10          111          Amit   East   Shoes      FASHION  3000.0  2024-01-07

In [9]:
if df.duplicated().sum()>0:
    df=df.drop_duplicates()
df

    Customer_ID Customer_Name Region Product     Category  Amount  Order_Date
0           101         rahul  North   shoes      Fashion  2500.0  2024-01-05
1           102         Pooja  south   Shirt      fashion  1500.0  2024-01-06
2           103          AMIT   East   Shoes      FASHION  3000.0  2024-01-07
3           104          Neha   West   Watch  Accessories  2000.0  2024-01-08
4           105         rahul  North   shoes      Fashion  2500.0  2024-01-05
5           106           NaN  South     Bag  Accessories  1800.0  2024-01-09
6           107          Ravi    NaN   Shoes      Fashion  2200.0  2024-01-10
7           108         Sneha   East     NaN      Fashion  2700.0  2024-01-11
8           109         Kiran   West   Watch          NaN  2100.0  2024-01-12
9           110         pooja  South   Shirt      fashion     NaN  2024-01-13
10          111          Amit   East   Shoes      FASHION  3000.0  2024-01-07

In [14]:
if df["Region"].isnull().any():
    df["Region"] = df["Region"].fillna("Unknown")

df

,Customer_ID,Customer_Name,Region,Product,Category,Amount,Order_Date
0,101,rahul,North,shoes,Fashion,2500.0,2024-01-05
1,102,Pooja,south,Shirt,fashion,1500.0,2024-01-06
2,103,AMIT,East,Shoes,FASHION,3000.0,2024-01-07
3,104,Neha,West,Watch,Accessories,2000.0,2024-01-08
4,105,rahul,North,shoes,Fashion,2500.0,2024-01-05
5,106,NaN,South,Bag,Accessories,1800.0,2024-01-09
6,107,Ravi,Unknown,Shoes,Fashion,2200.0,2024-01-10
7,108,Sneha,East,NaN,Fashion,2700.0,2024-01-11
8,109,Kiran,West,Watch,NaN,2100.0,2024-01-12
9,110,pooja,South,Shirt,fashion,NaN,2024-01-13
10,111,Amit,East,Shoes,FASHION,3000.0,2024-01-07

In [16]:
if df["Product"].isnull().any():
    df["Product"] = df["Product"].fillna("Unknown")

df

,Customer_ID,Customer_Name,Region,Product,Category,Amount,Order_Date
0,101,rahul,North,shoes,Fashion,2500.0,2024-01-05
1,102,Pooja,south,Shirt,fashion,1500.0,2024-01-06
2,103,AMIT,East,Shoes,FASHION,3000.0,2024-01-07
3,104,Neha,West,Watch,Accessories,2000.0,2024-01-08
4,105,rahul,North,shoes,Fashion,2500.0,2024-01-05
5,106,NaN,South,Bag,Accessories,1800.0,2024-01-09
6,107,Ravi,Unknown,Shoes,Fashion,2200.0,2024-01-10
7,108,Sneha,East,Unknown,Fashion,2700.0,2024-01-11
8,109,Kiran,West,Watch,NaN,2100.0,2024-01-12
9,110,pooja,South,Shirt,fashion,NaN,2024-01-13
10,111,Amit,East,Shoes,FASHION,3000.0,2024-01-07

In [ ]:
if df["Product"].isnull().any():
    df["Product"] = df["Product"].fillna("Unknown")

df