# Question 1 — Basic Merge Practice

Create two DataFrames:

customers:

| Customer_ID | Name |
|-------------|------|
| 1 | Aman |
| 2 | Priya |
| 3 | Rahul |

orders:

| Customer_ID | Amount |
|-------------|--------|
| 1 | 500 |
| 2 | 700 |
| 4 | 300 |

Tasks:

1 Perform inner merge  
2 Perform left merge  
3 Perform outer merge  
4 Compare number of rows in each result  

---

# Question 2 — Merge and Analyze

Using the same dataset:

1 Perform left join  
2 Identify customers with missing order values  
3 Replace missing values with 0  
4 Calculate total order amount  

---

# Question 3 — Multiple Key Merge

Create:

df1:

| ID | City | Sales |
|----|------|-------|
| 1 | Delhi | 100 |
| 1 | Mumbai | 200 |
| 2 | Delhi | 300 |

df2:

| ID | City | Target |
|----|------|--------|
| 1 | Delhi | 150 |
| 2 | Delhi | 350 |

Tasks:

1 Merge using ID only  
2 Merge using ID and City  
3 Compare both outputs  

---

# Question 4 — Duplicate Key Scenario

Create:

df1:

| ID | Product |
|----|---------|
| 1 | A |
| 1 | B |

df2:

| ID | Price |
|----|-------|
| 1 | 100 |
| 1 | 200 |

Tasks:

1 Perform inner merge  
2 Count number of rows  
3 Explain why rows increased  

---

# Question 5 — Concat Row-wise

Create two DataFrames:

df1:

Sales = [100, 200]

df2:

Sales = [300, 400]

Tasks:

1 Concatenate row-wise  
2 Concatenate using ignore_index=True  
3 Compare both outputs  

---

# Question 6 — Concat Column-wise

Create:

df1:

A = [1, 2]

df2:

B = [3, 4]

Tasks:

1 Concatenate column-wise  
2 Observe index alignment  
3 Explain output  

---

# Question 7 — Combine Monthly Data

Create three DataFrames:

Jan = [100, 200]  
Feb = [150, 250]  
Mar = [300, 350]  

Tasks:

1 Combine all months into one DataFrame  
2 Reset index  
3 Add a new column Month indicating source  

---

# Question 8 — Basic Pivot

Create dataset:

| Month | Product | Sales |
|------|--------|------|
| Jan | A | 100 |
| Jan | B | 200 |
| Feb | A | 150 |
| Feb | B | 250 |

Tasks:

1 Apply pivot  
2 Set Month as index  
3 Set Product as columns  
4 Use Sales as values  

---

# Question 9 — Pivot Table

Using same dataset:

1 Create pivot_table  
2 Use sum as aggregation  
3 Compare pivot vs pivot_table  

---

# Question 10 — Full Workflow (Easy but Long)

Create:

customers:

| ID | Name |
|----|------|
| 1 | Aman |
| 2 | Priya |
| 3 | Rahul |

sales:

| ID | Product | Amount |
|----|--------|--------|
| 1 | A | 100 |
| 1 | B | 200 |
| 2 | A | 300 |

Tasks:

1 Merge customers and sales  
2 Replace missing Amount with 0  
3 Create pivot table:  
   • index = Name  
   • columns = Product  
   • values = Amount  
4 Fill missing pivot values with 0

In [61]:
import pandas as pd
customers=pd.DataFrame({"customer_id":[1,2,3],
                        "name":["aman","priya","rahul"]})
orders=pd.DataFrame({"customer_id":[1,2,4],
                        "amount":[500,700,300]})

In [62]:
# task 1.1
pd.merge(customers,orders,how="inner",on="customer_id")

   customer_id   name  amount
0            1   aman     500
1            2  priya     700

In [63]:
# task 1.2
pd.merge(customers,orders,how="left",on="customer_id")

   customer_id   name  amount
0            1   aman   500.0
1            2  priya   700.0
2            3  rahul     NaN

In [64]:
# task 1.3
pd.merge(customers,orders,how="outer",on="customer_id")

   customer_id   name  amount
0            1   aman   500.0
1            2  priya   700.0
2            3  rahul     NaN
3            4    NaN   300.0

In [65]:
# q2-merge and analyze
# 2.1
pd.merge(customers,orders,how="left",on="customer_id")

   customer_id   name  amount
0            1   aman   500.0
1            2  priya   700.0
2            3  rahul     NaN

In [66]:
# 2.2
print("customers with missing order values")
merged=pd.merge(customers,orders,how="left",on="customer_id")
missing_orders=merged[merged["amount"].isna()]
missing_orders

customers with missing order values

   customer_id   name  amount
2            3  rahul     NaN

In [67]:
# 2.3
print("replce missing values with 0")
merged["amount"]=merged["amount"].fillna(0)
merged

replce missing values with 0

   customer_id   name  amount
0            1   aman   500.0
1            2  priya   700.0
2            3  rahul     0.0

In [68]:
print("calculate total order amount")
total_amount=merged.groupby("name")["amount"].sum()
total_amount

calculate total order amount

name
aman     500.0
priya    700.0
rahul      0.0
Name: amount, dtype: float64

In [69]:
df1=pd.DataFrame({"id":[1,1,2],
                  "city":["delhi","mumbai","delhi"],
                  "sales":[100,200,300]})
df2=pd.DataFrame({"id":[1,2],
                  "city":["delhi","delhi"],
                  "target":[150,350]
                })

In [70]:
# task 3.1
print("merge using id only")
pd.merge(df1,df2,on="id")

merge using id only

   id  city_x  sales city_y  target
0   1   delhi    100  delhi     150
1   1  mumbai    200  delhi     150
2   2   delhi    300  delhi     350

In [71]:
# task 3.2
print("merge using id and city")
pd.merge(df1,df2,on=["id","city"])

merge using id and city

   id   city  sales  target
0   1  delhi    100     150
1   2  delhi    300     350

In [72]:
# q4=duplicate key scenario
df3=pd.DataFrame({"id":[1,1],
                  "product":["A","B"]})
df4=pd.DataFrame({"id":[1,1],
                  "price":[100,200]})

In [73]:
# task 4.1
print("perform inner merge")
pd.merge(df3,df4,how="inner",on="id")

perform inner merge

   id product  price
0   1       A    100
1   1       A    200
2   1       B    100
3   1       B    200

In [74]:
# q5=concat row wise
df5=pd.DataFrame({"sales":[100,200]})
df6=pd.DataFrame({"sales":[300,400]})

In [75]:
# task 5.1
print("concate row-wise")
pd.concat([df5,df6],axis=0)

concate row-wise

   sales
0    100
1    200
0    300
1    400

In [76]:
# task 5.2
print("concate using ingnore_index=True")
pd.concat([df5,df6],ignore_index=True)

concate using ingnore_index=True

   sales
0    100
1    200
2    300
3    400

In [77]:
# q6=concate column-wise
df7=pd.DataFrame({"A":[1,2]})
df8=pd.DataFrame({"B":[3,4]})

In [78]:
# task 6.1
print("concate column-wise")
pd.concat([df7,df8],axis=1)

concate column-wise

   A  B
0  1  3
1  2  4

In [79]:
# q7=combine monthly data
df9=pd.DataFrame({"jan":[100,200]})
df10=pd.DataFrame({"feb":[150,250]})
df11=pd.DataFrame({"mar":[300,350]})

In [80]:
# task 7.1
print("combine all months into one dataframe")
pd.concat([df9,df10,df11])

combine all months into one dataframe

     jan    feb    mar
0  100.0    NaN    NaN
1  200.0    NaN    NaN
0    NaN  150.0    NaN
1    NaN  250.0    NaN
0    NaN    NaN  300.0
1    NaN    NaN  350.0

In [81]:
# task 7.2
print("reset index")
pd.concat([df9,df10,df11]).reset_index()

reset index

   index    jan    feb    mar
0      0  100.0    NaN    NaN
1      1  200.0    NaN    NaN
2      0    NaN  150.0    NaN
3      1    NaN  250.0    NaN
4      0    NaN    NaN  300.0
5      1    NaN    NaN  350.0

In [82]:
# task 7.3
print("add a new column month indicating source")
df_all = pd.concat([df9, df10, df11], ignore_index=True)
df_all

add a new column month indicating source

     jan    feb    mar
0  100.0    NaN    NaN
1  200.0    NaN    NaN
2    NaN  150.0    NaN
3    NaN  250.0    NaN
4    NaN    NaN  300.0
5    NaN    NaN  350.0

In [83]:
# q8=basic pivot
df12=pd.DataFrame({"month":["jan","jan","feb","feb"],
                   "product":["A","B","A","B"],
                  "sales":[100,200,150,250] })

In [84]:
# task8.1
print("apply pivot")
pd.pivot(df12,index="month",columns="product",values="sales")

apply pivot

product    A    B
month
feb      150  250
jan      100  200

In [85]:
# task8.2
print("apply pivot set month as index")
pd.pivot(df12,index="month",columns="product",values="sales")

apply pivot set month as index

product    A    B
month
feb      150  250
jan      100  200

In [86]:
# task8.3
print("apply pivot set product as column")
pd.pivot(df12,index="month",columns="product",values="sales")

apply pivot set product as column

product    A    B
month
feb      150  250
jan      100  200

In [87]:
# task8.4
print("apply pivot set sales as values")
pd.pivot(df12,index="month",columns="product",values="sales")

apply pivot set sales as values

product    A    B
month
feb      150  250
jan      100  200

In [88]:
# q9=pivot table
# task9.1
pd.pivot_table(df12,index="month",columns="product",values="sales")

product      A      B
month
feb      150.0  250.0
jan      100.0  200.0

In [89]:
# task9.2
pd.pivot_table(df12,index="month",columns="product",values="sales",aggfunc="sum")

product    A    B
month
feb      150  250
jan      100  200

In [90]:
# q10 full workflow
customers1=pd.DataFrame({"id":[1,2,3],
                         "name":["aman","priya","rahul"]})

sales1=pd.DataFrame({"id":[1,1,2],
                    "product":["A","B","A"],
                    "amount":[100,200,300]})

# task 10.1
print("merge customers and sales:")
merged=pd.merge(customers1,sales1,on="id",how="left")
merged

merge customers and sales:

   id   name product  amount
0   1   aman       A   100.0
1   1   aman       B   200.0
2   2  priya       A   300.0
3   3  rahul     NaN     NaN

In [91]:
# task 10.2
print("replace missing amount with 0:")
merged["amount"]=merged["amount"].fillna(0)
merged

replace missing amount with 0:

   id   name product  amount
0   1   aman       A   100.0
1   1   aman       B   200.0
2   2  priya       A   300.0
3   3  rahul     NaN     0.0

In [92]:
# task 10.3,10.4
print("create a pivot table:")
pivot=pd.pivot_table(merged,index="name",columns="product",values="amount",aggfunc="sum",fill_value=0)
pivot

create a pivot table:

product      A      B
name
aman     100.0  200.0
priya    300.0    0.0

In [93]:
# pandas practice q set-groupby & aggregations 
# q1
df13=pd.DataFrame({"region":["north","south","north","east"],
                   "revenue":[100,200,150,300]})

print("group by region")
df13.groupby("region")["revenue"].sum()

group by region

region
east     300
north    250
south    200
Name: revenue, dtype: int64

In [94]:
print("calculate total revenue:")
df13["revenue"].sum()

calculate total revenue:

np.int64(750)

In [95]:
# q2
print("find avg revenue per region:")
df13.groupby("region")["revenue"].mean()

find avg revenue per region:

region
east     300.0
north    125.0
south    200.0
Name: revenue, dtype: float64

In [96]:
# q3
df14=pd.DataFrame({"category":["A","A","B","B","A"],
                   "revenue":[100,200,150,250,300]})

print("group by category")
df14.groupby("category")["revenue"].sum()

group by category

category
A    600
B    400
Name: revenue, dtype: int64

In [97]:
print("find total revenue:")
df14["revenue"].sum()

find total revenue:

np.int64(1000)

In [98]:
# q4
print("find maximum revenue per category:")
df14.groupby("category")["revenue"].max()

find maximum revenue per category:

category
A    300
B    250
Name: revenue, dtype: int64

In [99]:
print("find minimum revenue per category:")
df14.groupby("category")["revenue"].min()

find minimum revenue per category:

category
A    100
B    150
Name: revenue, dtype: int64

In [100]:
# q5
df15=pd.DataFrame({"region":["north","south","north","south","east"],
                   "revenue":[100,200,150,250,300]})
# task
print("count number of row per rigion:")
df15.groupby("region").size()

count number of row per rigion:

region
east     1
north    2
south    2
dtype: int64

In [101]:
# q6
df16=pd.DataFrame({"region":["north","south","north","east"],
                    "category":["A","A","B","B"], 
                    "revenue":[100,200,150,300]}) 
print("groupby region and category")
df16.groupby(["region","category"])["revenue"].sum()

groupby region and category

region  category
east    B           300
north   A           100
        B           150
south   A           200
Name: revenue, dtype: int64

In [102]:
print("calculate total revenue")
df16["revenue"].sum()

calculate total revenue

np.int64(750)

In [103]:
# q7
print("calculate of mean revenue for each region")
df16.groupby("region")["revenue"].mean()

calculate of mean revenue for each region

region
east     300.0
north    125.0
south    200.0
Name: revenue, dtype: float64

In [104]:
# q8
df17=pd.DataFrame({"region":["north","south","north","east"],
                   "revenue":[100,200,150,300]})
# task
print("use group by with as_index=False")
df17.groupby("region",as_index=False)["revenue"].sum()

use group by with as_index=False

  region  revenue
0   east      300
1  north      250
2  south      200

In [105]:
# q9
print("sort groups in descending order of toal revenue")
df17.groupby("region")["revenue"].sum().sort_values(ascending=False)

sort groups in descending order of toal revenue

region
east     300
north    250
south    200
Name: revenue, dtype: int64

In [106]:
# q10
df18=pd.DataFrame({"region":["north","south","north","south","east"],
                   "revenue":[100,200,150,250,300]})
# task
print("use agg() to calculate sum and mean")
df18.groupby("region").agg({"revenue":["sum","mean"]})

use agg() to calculate sum and mean

       revenue
           sum   mean
region
east       300  300.0
north      250  125.0
south      450  225.0

In [107]:
# q11
print("rename aggregated column using named aggregatation")
df18.groupby("region").agg(total_revenue=("revenue","sum"),
                           avg_revenue=("revenue","mean"))

rename aggregated column using named aggregatation

        total_revenue  avg_revenue
region
east              300        300.0
north             250        125.0
south             450        225.0

In [108]:
# q12
df19=pd.DataFrame({"region":["north","south","north","south","east"],
                   "category":["A","A","B","B","A"],
                   "revenue":[100,200,150,250,300]})

# task
print("group by region and category")
group_r_c=df19.groupby(["region","category"])["revenue"].sum()
group_r_c

group by region and category

region  category
east    A           300
north   A           100
        B           150
south   A           200
        B           250
Name: revenue, dtype: int64

In [109]:
print("find total revenue")
df19["revenue"].sum()

find total revenue

np.int64(1000)

In [110]:
group_r_c.reset_index()

  region category  revenue
0   east        A      300
1  north        A      100
2  north        B      150
3  south        A      200
4  south        B      250

In [111]:
# q13
df20=pd.DataFrame({"region":["north","south","north","east"],
                   "revenue":[100,200,150,300]})
# task
print("use groupby and find count of revenue values")
df20.groupby("region")["revenue"].count()

use groupby and find count of revenue values

region
east     1
north    2
south    1
Name: revenue, dtype: int64

In [112]:
# q14
print("find standard deviation of revenue per region")
df20.groupby("region")["revenue"].std()

find standard deviation of revenue per region

region
east           NaN
north    35.355339
south          NaN
Name: revenue, dtype: float64